#!/usr/bin/env python3
"""The one fail-closed refusal marker used across `model/`, `tools/`, `fixtures/`.

`Refuse` is raised when a script cannot honour its contract on the input it
was given: an out-of-scope request, an unmet precondition, a pin that no
longer matches, a check whose verdict would otherwise have to be silently
downgraded. It is never used to continue past a problem — every runner
boundary catches it, prints the message, and exits 2, so a refusal is
recorded as evidence instead of being dropped.

The class is a bare `Exception` subclass on purpose: it carries no fields and
no methods, and the entire meaning of any given refusal lives in the message
constructed at the raise site. Import it rather than redefining it, so that
`except Refuse` in one module catches a refusal raised in another:

    sys.path.insert(0, REPO)          # repository root
    from refusal import Refuse        # noqa: E402

This module is deliberately dependency-free (no imports at all) so that it is
safe to import from any subsystem, including modules that run before the
pinned-interpreter re-exec in `oracle/oracle_common.py`.

TWO FILES DELIBERATELY KEEP THEIR OWN LOCAL `Refuse` (issue #258):
`model/effects/type-phaser/phaser_model.py` and
`model/effects/aw-4/logical4_model.py` each expose a `model_revision()` that
is a SHA-256 over their own source, and that word is pinned by committed
evidence records (`reports/SXT-028g/rtl-exactness.json`,
`reports/SXT-028k/*`). Editing either file — even by one import line —
invalidates those records, which can only be regenerated by re-running the
RTL comparison and negative-control tooling. Consolidating them is therefore
gated on that re-run, not on this module. `tests/test_shared_refuse.py`
pins that allowlist so the exception stays visible and cannot silently grow.
"""


class Refuse(Exception):
    """Fail-closed applicability refusal (exit 2 at the runner boundary)."""
