// GENERATED by tools/vel_param_corners.py -- not a frozen
// source file. The vel_rom function below is lifted VERBATIM out of
// rtl/voice/tb_vel.sv (or a mutant of it) so that this exhaustive enumeration
// tests that file's own integer expression rather than a second copy of it.
`timescale 1ns/1ps
module tb_vel_rom;
  localparam int FQ = 21;
  int unsigned qmul_count = 0;   // unused here; keeps the lifted text compiling
  integer m, fd;
  // velocity ROM contents (event rate): round-half-up(midi/127) in Q10.21
  function automatic signed [31:0] vel_rom(input logic [31:0] midi);
    logic [63:0] n;
    n = (64'(midi) << (FQ+1)) + 64'd127;
    vel_rom = 32'(n / 64'd254);
  endfunction
  initial begin
    fd = $fopen("tb_vel_rom_trace.txt", "w");
    for (m = 0; m < 128; m++) $fwrite(fd, "R %0d %0d\n", m, vel_rom(m));
    $fclose(fd);
    $display("DONE vel-rom-entries=128");
    $finish;
  end
endmodule
