// SXT-036 RTL velocity / release-velocity control-plane slice: per-voice-slot
// source registers (ms_velocity id 1, ms_releasevelocity id 30) and the
// voice route table (Filter 1 Cutoff 308 / Resonance 309 / FEG mod amount
// 310 / VCA Gain 298), implementing the SAME integer schedule as the frozen
// fixed-point model extension (model/voice/run_vel_model.py).
//
// Claim scope: simulated with iverilog; must match the frozen model EXACTLY
// (integer equality at every declared block-boundary checkpoint; enforced by
// tools/compare_vel_rtl_model.py). NOT synthesis-closed, NOT timing-closed;
// no gf180mcu FPGA/ASIC claim of any kind.
//
// Structure citations (read, not copied): surge@58914e59
//   src/common/dsp/SurgeVoice.cpp  ctor: state.fvel = velocity/127.f;
//       state.freleasevel = 0; velocitySource.init(0, fvel) (SLOW_EXP with
//       value == target: identity every block); releaseVelocitySource
//       .set_output(0, 0)
//   src/common/dsp/SurgeVoice.cpp  release(): releaseVelocitySource
//       .set_output(0, state.releasevelocity / 127.0f)
//   src/common/SurgeSynthesizer.cpp releaseNote: state.releasevelocity =
//       velocity for the key's voices, then release() of the gated voice
//   src/common/dsp/SurgeVoice.cpp  applyModulationToLocalcopy (voice list):
//       localcopy[dst] += depth * source
//
// Per-instance state: one {vel_q, relvel_q} register pair PER VOICE SLOT
// (a SurgeVoice owns its velocity and release-velocity sources); nothing is
// shared across slots or scenes. The broken-state mutant
// (rtl/voice/tb_vel_shared_mutant.sv, generated by
// tools/vel_negative_controls.py) collapses them to one scene-wide pair and
// must FAIL exactness.
//
// Velocity quantization (event rate only, never audio rate):
//   q = (midi * 2^22 + 127) / 254  ==  round-half-up(midi/127 * 2^21)
// i.e. a 128-entry Q10.21 ROM in hardware; modeled here as the constant
// divide the ROM would tabulate (identical integer for every midi 0..127).
//
// Stimulus (declared control-plane boundary; emitted by run_vel_model.py):
//   rtl/vel_init.hex    [total_blocks]
//   rtl/vel_routes.hex  n_routes, then (src_code, dest_code, depth_q21)
//                       (src 0=velocity 1=release velocity;
//                        dest 0=cutoff 1=reso 2=fegmod 3=vca)
//   rtl/vel_ctrl.hex    per block: b, then per slot
//                       [run, create, vel_midi, release, relvel_midi]
`timescale 1ns/1ps

module tb_vel;

  localparam int FQ     = 21;
  localparam int NSLOTS = 8;
  localparam int SW     = 5;
  localparam int STRIDE = 1 + NSLOTS*SW;

  int unsigned qmul_count = 0;

  function automatic signed [31:0] qmul_sh(input signed [31:0] a,
                                           input signed [31:0] b,
                                           input integer sh);
    logic signed [63:0] p, r;
    qmul_count++;
    p = a * b;
    r = p >>> sh;
    if      (r > 64'sd2147483647)  qmul_sh = 32'sd2147483647;
    else if (r < -64'sd2147483648) qmul_sh = -32'sd2147483648;
    else                           qmul_sh = r[31:0];
  endfunction

  // velocity ROM contents (event rate): round-half-up(midi/127) in Q10.21
  function automatic signed [31:0] vel_rom(input logic [31:0] midi);
    logic [63:0] n;
    n = (64'(midi) << (FQ+1)) + 64'd127;
    vel_rom = 32'(n / 64'd254);
  endfunction

  // ------------------------------------------------------------------ state
  logic [31:0] vel_init  [0:0];
  logic [31:0] vel_route [0:192];
  logic [31:0] ctrl_mem  [0:2000000];

  // per-instance source registers (one pair per voice slot)
  logic signed [31:0] vel_q    [NSLOTS];
  logic signed [31:0] relvel_q [NSLOTS];

  integer fd;
  integer b, s, k, n_routes, ci, base;
  logic signed [31:0] sum_cut, sum_reso, sum_emod, sum_vca, term, depth, srcv;
  logic [31:0] src, dst;

  initial begin
    $readmemh("rtl/vel_init.hex",   vel_init);
    $readmemh("rtl/vel_routes.hex", vel_route);
    $readmemh("rtl/vel_ctrl.hex",   ctrl_mem);
    fd = $fopen("tb_vel_trace.txt", "w");
    if (vel_init[0] === 32'hxxxxxxxx) $fatal(1, "vel_init.hex truncated");
    n_routes = int'(vel_route[0]);
    if (n_routes > 64) $fatal(1, "route table too large: %0d", n_routes);
    for (s = 0; s < NSLOTS; s++) begin vel_q[s] = 0; relvel_q[s] = 0; end
    run();
    $fclose(fd);
    $display("DONE vel-qmuls=%0d", qmul_count);
    $finish;
  end

  task automatic run;
    int total_blocks;
    total_blocks = int'(vel_init[0]);
    ci = 0;
    for (b = 0; b < total_blocks; b++) begin
      if (ctrl_mem[ci] === 32'hxxxxxxxx)
        $fatal(1, "vel ctrl stream exhausted at block %0d", b);
      if (int'(ctrl_mem[ci]) != b)
        $fatal(1, "vel ctrl desync at block %0d (got %0d)", b, ctrl_mem[ci]);
      // event dispatch: construction latches velocity and clears release
      // velocity; release latches release velocity (same block's pass reads it)
      for (s = 0; s < NSLOTS; s++) begin
        base = ci + 1 + s*SW;
        if (ctrl_mem[base+1][0]) begin
          vel_q[s]    = vel_rom(ctrl_mem[base+2]);
          relvel_q[s] = 0;
        end
        if (ctrl_mem[base+3][0]) begin
          relvel_q[s] = vel_rom(ctrl_mem[base+4]);
        end
      end
      // per-voice control pass: route sums from THIS slot's registers
      for (s = 0; s < NSLOTS; s++) begin
        base = ci + 1 + s*SW;
        if (ctrl_mem[base][0]) begin
          sum_cut = 0; sum_reso = 0; sum_emod = 0; sum_vca = 0;
          for (k = 0; k < n_routes; k++) begin
            src   = vel_route[1 + k*3];
            dst   = vel_route[2 + k*3];
            depth = 32'(vel_route[3 + k*3]);
            srcv  = (src == 0) ? vel_q[s] : relvel_q[s];
            term  = qmul_sh(depth, srcv, FQ);
            case (dst)
              0: sum_cut  = sum_cut  + term;
              1: sum_reso = sum_reso + term;
              2: sum_emod = sum_emod + term;
              default: sum_vca = sum_vca + term;
            endcase
          end
          $fwrite(fd, "V %0d %0d %0d %0d\n", b, s, vel_q[s], relvel_q[s]);
          $fwrite(fd, "S %0d %0d %0d %0d %0d %0d\n",
                  b, s, sum_cut, sum_reso, sum_emod, sum_vca);
        end
      end
      ci += STRIDE;
    end
  endtask

endmodule
