#!/usr/bin/env python3
"""SXT-040 Sine oscillator family tests (issue #74).

Covers: the 32-mode shape transcription against a float32-emulated model of
the pinned SSE code, the frozen model's declared parameter classes and
fail-closed refusals, the pitch-extend/pan-law/quadrant-divide semantics,
RTL-vs-model exactness on deterministic smoke configurations (iverilog
required, skipped when absent), and the out-of-class refusal controls (all
graph-level, no oracle needed). Oracle-dependent reference budget checks are
NOT run here (committed artifacts under reports/SXT-040/artifacts/ are
regenerated by tools/run_sxt040_checks.py).
"""

import json
import math
import os
import shutil
import struct
import subprocess
import sys
import tempfile

import pytest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from model.voice import voice_model as vm  # noqa: E402

SINE = os.path.join(REPO, "model", "oscillators", "sine")
TB = os.path.join(REPO, "rtl", "oscillators", "sine", "tb_sine.sv")
MUTANT = os.path.join(REPO, "rtl", "oscillators", "sine",
                      "sine_broken_mutant.sv")
sys.path.insert(0, SINE)

import sine_model as sm  # noqa: E402

HAS_IVERILOG = all(shutil.which(x) for x in ("iverilog", "vvp"))
INPUTS = sorted(os.listdir(os.path.join(SINE, "inputs")))

F32 = lambda x: struct.unpack("f", struct.pack("f", x))[0]  # noqa: E731
ONE = 1 << 21


def _mul(a, b):
    return F32(a * b)


def _add(a, b):
    return F32(a + b)


def _sub(a, b):
    return F32(a - b)


def _div(a, b):
    return F32(a / b)


def ref_shape(mode, s, c):
    """float32-emulated transcription of the pinned
    valueFromSinAndCosForMode<mode> (SineOscillator.cpp)."""
    s2x = _mul(2.0, _mul(s, c))
    c2x = _sub(1.0, _mul(2.0, _mul(s, s)))

    def m1(y):
        cc = _sub(1.0, _mul(2.0, _mul(y, y)))
        return _mul(0.5, _sub(1.0, cc)) if y >= 0 else _mul(0.5, _sub(cc, 1.0))

    def m3(y):
        cc = _sub(1.0, _mul(2.0, _mul(y, y)))
        return _mul(0.5, _sub(1.0, cc)) if y >= 0 else 0.0

    def quad(sv, cv):
        sl = 1 if sv <= 0 else 0
        cl = 1 if cv <= 0 else 0
        return 3 * sl + cl - 2 * sl * cl + 1

    if mode == 0:
        return s
    if mode == 1:
        return m1(s)
    if mode == 2:
        return s if s >= 0 else 0.0
    if mode == 3:
        return m3(s)
    if mode == 4:
        return s2x if s >= 0 else 0.0
    if mode == 5:
        return m1(s2x) if s >= 0 else 0.0
    if mode == 6:
        return abs(s2x if s >= 0 else 0.0)
    if mode == 7:
        return abs(m1(s2x) if s >= 0 else 0.0)
    if mode == 8:
        return _sub(_mul(2.0, s if s >= 0 else 0.0), 1.0)
    if mode == 9:
        return s if _mul(s, c) <= 0 else 0.0
    if mode == 10:
        return s if _mul(s, c) >= 0 else 0.0
    if mode == 11:
        return _sub(_mul(2.0, m3(s)), 1.0)
    if mode == 12:
        return _mul(s2x, 1.0 if c >= 0 else -1.0)
    if mode == 13:
        v = _mul(-1.0 if s <= 0 else 1.0, s2x)
        return v if s2x >= 0 else 0.0
    if mode == 14:
        return abs(c2x) if s >= 0 else 0.0
    if mode == 15:
        return (_sub(1.0, s) if s >= 0 else _sub(-1.0, s)) if c >= 0 else 0.0
    if mode == 16:
        return (_sub(1.0, s) if s >= 0 else _sub(c, 1.0)) if c >= 0 else 0.0
    if mode == 17:
        return _sub(1.0 if s >= 0 else -1.0, s)
    if mode == 18:
        return c if c <= 0 else _mul(1.0 if s >= 0 else -1.0, s2x)
    if mode == 19:
        s4x = _mul(2.0, _mul(s2x, c2x))
        return (s2x if c >= 0 else -s4x) if s >= 0 else s
    if mode == 20:
        sbc = _mul(s, c)
        return s if sbc >= 0 else (1.0 if s >= 0 else -1.0)
    if mode == 21:
        sbc = _mul(s, c)
        return (1.0 if s >= 0 else -1.0) if sbc >= 0 else s
    if mode == 22:
        return s if c >= 0 else 0.0
    if mode == 23:
        return s if c <= 0 else 0.0
    if mode == 24:
        return _sub(1.0, s) if s >= 0 else s
    if mode == 25:
        return _div(s2x, float(quad(s, c))) if s >= 0 else 0.0
    if mode == 26:
        return 0.0 if (s <= 0 and c <= 0) else s
    if mode == 27:
        return _div(s2x, float(quad(s, c)))
    if mode == 28:
        sw = 1.0 if s >= 0 else -1.0
        pm = 1.0 if _mul(s, c) < 0 else -1.0
        return _add(sw, _mul(pm, c))
    if mode == 29:
        h1 = s >= 0
        q2 = h1 and c <= 0
        fh = 1.0 if h1 else 0.0
        cx = _mul(_mul(fh, c), _add(-1.0, _mul(2.0, 1.0 if q2 else 0.0)))
        return _add(fh, cx)
    if mode in (30, 31):
        sw = 1.0 if s2x >= 0 else -1.0
        pm = 1.0 if _mul(s2x, c2x) < 0 else -1.0
        v1 = _add(sw, _mul(pm, c2x))
        r = v1 if s >= 0 else 0.0
        return abs(r) if mode == 31 else r
    raise RuntimeError(mode)


def _synth_inputs(tmp, **over):
    """Deterministic declared-class configuration (test configuration; the
    parameter values are drawn from the recovery-basis presets' observed
    ranges — see model/oscillators/sine/README.md)."""
    d = {
        "schema_version": 1, "issue": "SXT-040", "carrier": "test",
        "slot": 0, "preset_path": "test-configuration",
        "preset_census_blob_sha1": "0",
        "octave": -1, "scene_octave": 0, "keytrack": True,
        "pitch_param": 0.0, "pitch_extend": False, "retrigger": True,
        "shape": 8, "fb": 0.0, "fb_extend": False, "fmmode": 1,
        "lowcut": -60.0, "highcut": 70.0, "unison_detune": 0.033928,
        "extend_detune": False, "absolute_detune": False, "unison": 4,
        "character": 0, "drift": 0.0, "o_level": 0.8, "level_pfg": 0.0,
        "pan": 0.0, "scene_volume": 0.9, "vca_db": 3.0,
        "vca_velsense": 0.0, "master_db": -2.0,
        "adsr": {"a": -5.2, "d": -3.0, "s": 0.6, "r": -3.5, "a_s": 1.0,
                 "d_s": 1.0, "r_s": 2.0, "mode": 0.0},
    }
    d.update(over)
    path = os.path.join(tmp, "synth.json")
    with open(path, "w") as f:
        json.dump(d, f)
    return path


def _run_model(inputs, out, seq="seq-notes-repeated-v1", blocks=96,
               env=None):
    e = dict(os.environ)
    if env:
        e.update(env)
    return subprocess.run(
        [sys.executable, os.path.join(SINE, "run_model.py"),
         "--inputs", inputs, "--sequence", seq, "--out-dir", out,
         "--rtl", "--max-blocks", str(blocks)],
        capture_output=True, text=True, env=e, cwd=REPO)


def _compare(run_dir, tb=TB):
    return subprocess.run(
        [sys.executable, os.path.join(REPO, "tools",
                                      "compare_sine_rtl_model.py"),
         "--run-dir", run_dir, "--tb", tb],
        capture_output=True, text=True, cwd=REPO)


# --------------------------------------------------------------- model ---

def test_shape_transcription_matches_pinned_sse_semantics():
    # all 32 modes vs a float32-emulated model of valueFromSinAndCosForMode;
    # points off the sub-LSB sign boundary (a declared deviation) and off
    # the |s|,|c| ~ 1e-3 product-underflow corner (unreachable from
    # sin/cos pairs on the unit circle - both |s|,|c| tiny cannot occur)
    import random
    rng = random.Random(11)
    lsb = 1.0 / ONE
    pts = [(rng.uniform(-1, 1), rng.uniform(-1, 1)) for _ in range(4000)]
    for _ in range(800):
        s = rng.choice([rng.uniform(2 * lsb, 1), rng.uniform(-1, -2 * lsb),
                        0.0])
        c = rng.choice([rng.uniform(2 * lsb, 1), rng.uniform(-1, -2 * lsb),
                        0.0])
        pts.append((s, c))
    for mode in range(32):
        for s, c in pts:
            want = ref_shape(mode, s, c)
            got = sm.shape_out(mode, vm.qint(s), vm.qint(c)) / ONE
            assert abs(got - want) <= 30e-6 * max(1.0, abs(want)), \
                (mode, s, c, want, got)


def test_mode27_quadrant_divide_is_integer_scaled():
    # the quadrant divisor is a plain integer 1..4 (fb=0 in vm.qdiv), not a
    # Q10.21 word - regression guard for the 2^21 scaling bug
    s = vm.qint(0.5)
    c = vm.qint(0.5)
    s2x = 2 * ((s * c + (1 << 20)) >> 21)   # the model's shl1(qmul(s, c))
    got = sm.shape_out(27, s, c)
    want = vm.qdiv(s2x, 1, fb=0)  # quadrant(s>0, c>0) = 1
    assert got == want
    got25 = sm.shape_out(25, s, c)
    assert got25 == want


def test_pitch_param_extend_semantics():
    # Mystery 4: pitch_param 1.075 with extend_range FALSE = +1.075 st
    d = json.loads(open(os.path.join(SINE, "inputs", "mystery4.json")).read()
                   ) if os.path.exists(os.path.join(
                       SINE, "inputs", "mystery4.json")) else None
    assert d is None or (d["pitch_extend"] is False
                         and abs(d["pitch_param"] - 1.0750559568405151) < 1e-6)
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        i = sm.Inputs(_synth_inputs(tmp, pitch_param=1.075,
                                    pitch_extend=False,
                                    octave=-1, scene_octave=-1))
        o = sm.SineOsc(i, 60)
        assert abs(o.pitch - (60 - 24 + 1.075)) < 1e-9
        i2 = sm.Inputs(_synth_inputs(tmp, pitch_param=1.075,
                                     pitch_extend=True,
                                     octave=-1, scene_octave=-1))
        o2 = sm.SineOsc(i2, 60)
        assert abs(o2.pitch - (60 - 24 + 12.9)) < 1e-6


def test_unison_constants_match_unisonsetup():
    with tempfile.TemporaryDirectory() as tmp:
        inp = sm.Inputs(_synth_inputs(tmp, unison=6, unison_detune=0.2))
        o = sm.SineOsc(inp, 48)
        att = o.out_attenuation / float(ONE)
        assert abs(att - 1.0 / (6 ** 0.5)) < 1e-6
        dets = [round(v, 6) for v in o.voice_detune]
        assert dets == [round(0.2 * (2.0 / 5 * v - 1.0), 6) for v in range(6)]


def test_unison_pan_is_mono_inert():
    # UnisonSetup linear pan law: (panL + panR)/2 = 1 for every voice, so
    # the mono fold cancels it structurally (sum of weights = n)
    with tempfile.TemporaryDirectory() as tmp:
        for uni in (2, 3, 9):
            inp = sm.Inputs(_synth_inputs(tmp, unison=uni))
            osc = sm.SineOsc(inp, 60)
            # every voice contributes with weight exactly 1 to the mono bus
            assert osc.out_attenuation == vm.qint(F32(1.0 / F32(
                math.sqrt(1.0 * uni))))


def test_refusals_are_fail_closed(tmp_path):
    cases = (
        ({"unison": 17}, "unison"),
        ({"absolute_detune": True}, "absolute"),
        ({"drift": 0.3}, "drift"),
        ({"character": 2}, "Bright"),
        ({"shape": 32}, "shape"),
        ({"shape": -1}, "shape"),
        ({"fmmode": 2}, "behavior"),
        ({"adsr": {"a": -5.2, "d": -3.0, "s": 0.6, "r": -3.5, "a_s": 1.0,
                   "d_s": 3.0, "r_s": 2.0, "mode": 0.0}}, "decay shape"),
        ({"adsr": {"a": -5.2, "d": -3.0, "s": 0.6, "r": -3.5, "a_s": 3.0,
                   "d_s": 1.0, "r_s": 2.0, "mode": 0.0}}, "attack shape"),
    )
    for over, msg in cases:
        d = json.loads(open(_synth_inputs(tmp_path)).read())
        d.update(over)
        p = os.path.join(tmp_path, "m.json")
        json.dump(d, open(p, "w"))
        i = sm.Inputs(p)
        if "adsr" in over:
            with pytest.raises(RuntimeError, match=msg):
                sm.AdsrSine(i.adsr, "aeg")
        else:
            with pytest.raises(RuntimeError, match=msg):
                sm.SineOsc(i, 60)


def test_inputs_are_census_pinned_and_retriggered():
    for name in INPUTS:
        d = json.loads(open(os.path.join(SINE, "inputs", name)).read())
        assert d["preset_census_blob_sha1"] != "0", name
        assert d["retrigger"] is True, name
        assert d["drift"] == 0.0, name
        assert 1 <= d["unison"] <= 16, name
        assert not d["absolute_detune"], name
        assert d["fmmode"] in (0, 1), name
        assert 0 <= d["shape"] <= 31, name
        # every committed carrier input must carry the route override and
        # read back route_slot == 1 (the serial-1 A path)
        overrides = dict(d["declared_overrides"])
        assert ("route_slot_1", True) in [(k, v) for k, v in
                                          d["declared_overrides"]], name


# ----------------------------------------------------------------- RTL ---

@pytest.mark.skipif(not HAS_IVERILOG, reason="iverilog/vvp not present")
def test_rtl_vs_model_exact_smoke_modern(tmp_path):
    inputs = _synth_inputs(tmp_path)
    out = str(tmp_path / "run")
    r = _run_model(inputs, out)
    assert r.returncode == 0, r.stderr
    c = _compare(out)
    assert c.returncode == 0, c.stdout + c.stderr


@pytest.mark.skipif(not HAS_IVERILOG, reason="iverilog/vvp not present")
def test_rtl_vs_model_exact_smoke_legacy_unison9(tmp_path):
    # legacy behavior with a 9-voice stack: per-voice quadrature state +
    # playingramp machinery (the class no committed corpus fixture isolates)
    inputs = _synth_inputs(tmp_path, shape=0, fmmode=0, unison=9,
                           unison_detune=0.4)
    out = str(tmp_path / "run")
    r = _run_model(inputs, out)
    assert r.returncode == 0, r.stderr
    c = _compare(out)
    assert c.returncode == 0, c.stdout + c.stderr


@pytest.mark.skipif(not HAS_IVERILOG, reason="iverilog/vvp not present")
def test_negative_control_mutant_fails_exactness(tmp_path):
    inputs = _synth_inputs(tmp_path)
    out = str(tmp_path / "run")
    assert _run_model(inputs, out).returncode == 0
    c = _compare(out, tb=MUTANT)
    assert c.returncode == 1, "mutant must FAIL the exactness check"


def test_negative_control_shape_migration_confusion_fails_budget(tmp_path):
    # render the tentacles fixture with the RAW pre-migration shape value
    # (the sine_shape_remap confusion; cf. Arp 2 raw 1 -> normalized 28):
    # the model-vs-reference budget check must FAIL
    ref = os.path.join(REPO, "reports", "SXT-040", "artifacts",
                       "tentacles__seq-notes-coverage-v1-ref.wav")
    if not os.path.exists(ref):
        pytest.skip("committed reference render not present")
    inputs = os.path.join(SINE, "inputs", "tentacles.json")
    out = str(tmp_path / "nc")
    r = _run_model(inputs, out, seq="seq-notes-coverage-v1", blocks=512,
                   env={"SXT040_NC_SHAPE_RAWVALUE": "1"})
    assert r.returncode == 0, r.stderr
    c = subprocess.run(
        [sys.executable, os.path.join(REPO, "tools",
                                      "compare_audio_reference.py"),
         "--ref", ref, "--model", os.path.join(out, "model.wav")],
        capture_output=True, text=True)
    assert "FAIL against proposed budgets" in c.stdout


def test_negative_control_classic_substitution_fails_budget(tmp_path):
    # drive the badnews fixture parameters with the landed SXT-033 Classic
    # arithmetic: the budget check against the Sine reference must FAIL
    ref = os.path.join(REPO, "reports", "SXT-040", "artifacts",
                       "badnews__seq-notes-repeated-v1-ref.wav")
    if not os.path.exists(ref):
        pytest.skip("committed reference render not present")
    sys.path.insert(0, os.path.join(REPO, "model", "oscillators", "classic"))
    import classic_model as cm  # noqa: E402
    d = json.loads(open(os.path.join(SINE, "inputs", "badnews.json")).read())
    d.update({"issue": "SXT-033-negative-control-of-SXT-040", "shape": 0,
              "pw": 0.5, "pw2": 0.5, "submix": 0.0, "sync": 0.0})
    p = os.path.join(tmp_path, "classic-sub.json")
    json.dump(d, open(p, "w"))
    inp = cm.Inputs(p)
    assert inp.slot == 2 and inp.unison == 1
    out = str(tmp_path / "nc")
    r = subprocess.run(
        [sys.executable, os.path.join(REPO, "model", "oscillators",
                                      "classic", "run_model.py"),
         "--inputs", p, "--sequence", "seq-notes-repeated-v1",
         "--out-dir", out, "--max-blocks", "512"],
        capture_output=True, text=True, cwd=REPO)
    assert r.returncode == 0, r.stderr
    c = subprocess.run(
        [sys.executable, os.path.join(REPO, "tools",
                                      "compare_audio_reference.py"),
         "--ref", ref, "--model", os.path.join(out, "model.wav")],
        capture_output=True, text=True)
    assert "FAIL against proposed budgets" in c.stdout


def test_out_of_class_presets_refused():
    # all four refusal controls refuse at the committed-graphs level (no
    # oracle needed): playmode (mortsnare, arp2) and live voice routes
    # (alone, mystery4)
    for carrier, msg in (
            ("mortsnare", "playmode"),
            ("arp2", "playmode"),
            ("alone", "Amp EG Attack"),
            ("mystery4", "Amp EG Attack")):
        r = subprocess.run(
            [sys.executable, os.path.join(SINE, "extract_inputs.py"),
             "--carrier", carrier,
             "--out", os.path.join(tempfile.gettempdir(), carrier + ".json")],
            capture_output=True, text=True, cwd=REPO)
        combined = r.stdout + r.stderr
        if "ORACLE_SURGE_DIR" in combined:
            pytest.skip("external pinned oracle not present")
        assert r.returncode == 2, (carrier, combined)
