#!/usr/bin/env python3
"""Issue #360 public-command probe: stale/no-output trace controls.

Runs the public shared-wrapper leaf `tools/compare_mw_rtl_model.py` (one of
the five `run_leaf_comparison()` leaves) with REAL iverilog/vvp, three times
against ONE reused run directory:

  1. healthy   -- the leaf's own rtl/voice/tb_mw.sv; writes a fresh
                  tb_mw_trace.txt and is compared with integer equality.
  2. stale     -- the trace from (1) is left in place (a known passing prior
                  trace) and the leaf is pointed at NO_OUTPUT_TB, an original
                  testbench that exits 0 without opening or writing the
                  expected trace.
  3. empty-dir -- the same no-output testbench with no trace present.

For each it records the command, exit status, the verdict JSON, and the
sha256 of `tb_mw_trace.txt` before and after the run. The check targeted by
the negative controls is "comparison is decided only from a trace THIS
invocation wrote"; (2) and (3) must exit nonzero with
`comparison: NOT_RUN` and a `missing current-run output` reason, and (2) must
NOT report PASS from the trace (1) left behind.

The model run dir is generated by model/voice/run_mw_model.py (needs numpy).
Nothing here is evidence about DSP fidelity, preset support or hardware.

Usage:
  python3 probe-stale-trace.py --work DIR --out TRANSCRIPT
"""

import argparse
import hashlib
import json
import os
import platform
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))
RUNNER = os.path.join(REPO, "model", "voice", "run_mw_model.py")
LEAF = os.path.join(REPO, "tools", "compare_mw_rtl_model.py")
SEQ = "seq-modwheel-v1"
TRACE = "tb_mw_trace.txt"

NO_OUTPUT_TB = """\
// Issue #360 negative-control testbench (original to this repository):
// exits 0 after a DONE line, never opens or writes tb_mw_trace.txt.
module tb_mw_no_output;
  initial begin
    $display("DONE no-output control");
    $finish;
  end
endmodule
"""


def sha(path):
    if not os.path.exists(path):
        return "ABSENT"
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def tool_version(cmd):
    try:
        r = subprocess.run(cmd, capture_output=True, text=True)
        return (r.stdout or r.stderr).splitlines()[0].strip()
    except (OSError, IndexError) as exc:
        return "UNAVAILABLE (%s)" % exc


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--work", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    lines = []
    work = os.path.abspath(args.work)
    # host-specific work paths are scrubbed so the transcript is portable
    scrub = [(os.path.relpath(work, REPO), "<work>"), (work, "<work>")]

    def log(s=""):
        for old, new in scrub:
            s = s.replace(old, new)
        print(s)
        lines.append(s)

    run_dir = os.path.join(os.path.abspath(args.work), "mw")
    head = subprocess.run(["git", "-C", REPO, "rev-parse", "HEAD"],
                          capture_output=True, text=True).stdout.strip()
    dirty = subprocess.run(["git", "-C", REPO, "status", "--porcelain",
                            "--", "tools", "rtl", "model"],
                           capture_output=True, text=True).stdout.strip()
    log("# issue #360 public-command probe: %s" % os.path.relpath(LEAF, REPO))
    log("git HEAD: %s (tools/rtl/model worktree dirty: %s)"
        % (head, "yes" if dirty else "no"))
    log("python: %s %s" % (platform.python_implementation(),
                           platform.python_version()))
    log("iverilog: %s" % tool_version(["iverilog", "-V"]))
    # identified by git blob id, NOT sha256: a sha256 of the helper's bytes
    # in a committed record would make it an (unregistered) byte-frozen pin
    blob = subprocess.run(
        ["git", "-C", REPO, "hash-object",
         os.path.join(REPO, "tools", "_rtl_compile_common.py")],
        capture_output=True, text=True).stdout.strip()
    log("helper tools/_rtl_compile_common.py git blob: %s" % blob)
    log("run dir: <work>/mw (reused across all three runs)")
    log("")

    r = subprocess.run([sys.executable, RUNNER, "--sequence", SEQ,
                        "--out-dir", run_dir], capture_output=True, text=True)
    log("model runner: %s --sequence %s exit=%d"
        % (os.path.relpath(RUNNER, REPO), SEQ, r.returncode))
    if r.returncode != 0:
        log("BLOCKED: model runner failed: %s" % r.stderr[-500:])
        _write(args.out, lines)
        return 2

    no_output_tb = os.path.join(os.path.abspath(args.work),
                                "tb_mw_no_output.sv")
    with open(no_output_tb, "w") as f:
        f.write(NO_OUTPUT_TB)

    trace = os.path.join(run_dir, TRACE)
    results = {}

    def leaf(tag, tb=None):
        out = os.path.join(os.path.abspath(args.work), tag + "-verdict.json")
        cmd = [sys.executable, LEAF, "--run-dir", run_dir, "--out", out]
        if tb:
            cmd += ["--tb", tb]
        before = sha(trace)
        p = subprocess.run(cmd, capture_output=True, text=True)
        after = sha(trace)
        try:
            with open(out) as f:
                verdict = json.load(f)
        except (OSError, ValueError):
            verdict = None
        shown = ["python3", os.path.relpath(LEAF, REPO), "--run-dir",
                 "<work>/mw", "--out", "<work>/%s-verdict.json" % tag]
        if tb:
            shown += ["--tb", "<work>/" + os.path.basename(tb)]
        log("## %s" % tag)
        log("command: %s" % " ".join(shown))
        log("exit: %d" % p.returncode)
        log("trace sha256 before: %s" % before)
        log("trace sha256 after:  %s" % after)
        log("verdict json:")
        log(json.dumps(verdict, indent=2))
        log("")
        results[tag] = (p.returncode, verdict, before, after)

    leaf("healthy")
    healthy_trace_sha = results["healthy"][3]
    leaf("stale", no_output_tb)
    if os.path.exists(trace):
        os.remove(trace)
    leaf("empty-dir", no_output_tb)

    checks = []
    rc, v, _, after = results["healthy"]
    checks.append(("healthy: exit 0, comparison PASS, fresh trace written",
                   rc == 0 and v and v["comparison"] == "PASS"
                   and after != "ABSENT"))
    for tag in ("stale", "empty-dir"):
        rc, v, before, after = results[tag]
        ok = (rc != 0 and v is not None and v["comparison"] == "NOT_RUN"
              and v["verdict"] == "FAIL" and len(v["sim_fails"]) == 1
              and v["sim_fails"][0].startswith(
                  "missing current-run output: " + TRACE)
              and set(v["checked"].values()) == {0} and after == "ABSENT")
        checks.append(("%s: exit!=0, NOT_RUN, named missing output, zero "
                       "checked, no trace left" % tag, ok))
    rc, v, before, _ = results["stale"]
    checks.append(("stale: pre-seeded trace was the healthy run's passing "
                   "trace and was NOT reported as PASS",
                   before == healthy_trace_sha and before != "ABSENT"
                   and v is not None and v["comparison"] != "PASS"))
    log("## checks")
    for name, ok in checks:
        log("%s  %s" % ("PASS" if ok else "FAIL", name))
    overall = all(ok for _, ok in checks)
    log("RESULT %s" % ("PASS" if overall else "FAIL"))
    _write(args.out, lines)
    return 0 if overall else 1


def _write(path, lines):
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    sys.exit(main())
