#!/usr/bin/env python3
"""SXT-021 negative controls — every control must FAIL the check it targets.

Runs three live negative controls and writes the transcript to
reports/sxt-021/negative-controls.txt:

  NC1 (issue #14 acceptance): an event burst exceeding the DECLARED
      reserve (8 events/block) must produce a DETECTED, BOUNDED overload —
      explicit statuses / drop records, accounting that does not close —
      never silent corruption. Two variants: above-reserve (spill, no
      drops) and above-queue-capacity (explicit in-model AND in-DUT drops).

  NC2: a stub slot mislabeled as real DSP (or a stale/silent stub) emitting
      all-zero output where the declared counter-stub pattern is expected
      must be CAUGHT by the output check — the checker never trusts the
      engine's claimed name.

  NC3: an RTL-vs-model divergence injected through ONE queue-depth constant
      (rtl/control/control_broken_mutant.sv, depth 15) must FAIL the
      comparator on the committed fixtures.

Exit code 0 only if every control demonstrably fails its check. Requires
iverilog for NC3 (skipped as NOT_RUN otherwise — never reported as a pass).
"""

import json
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from model.control import render_sequence  # noqa: E402
from model.control.engine_stub_counter import CounterStubEngine  # noqa: E402
from model.control.engine_stub_silent import SilentStubEngine  # noqa: E402
from tools.compare_control_rtl import run_comparison  # noqa: E402

REPORTS = os.path.join(REPO, "reports", "sxt-021")
OUT = os.path.join(REPORTS, "negative-controls.txt")


class MislabeledRealDspEngine:
    """NC2 vehicle: the SILENT stub presenting itself as real DSP.

    The claimed name is a lie — which is exactly the point: the output
    check must catch the dead slot regardless of what the engine claims
    to be (naming conventions help reviewers; they do not replace checks).
    """

    name = "surge-voice-real-dsp [UNVERIFIED CLAIM]"

    def process_block(self, b, vcount, sample_index0):
        return SilentStubEngine().process_block(b, vcount, sample_index0)


def load_seq(ident):
    p = os.path.join(REPO, "fixtures", "control", "sequences",
                     ident + ".json")
    with open(p) as f:
        return json.load(f)


def output_check(trace, out_bytes):
    """Declared counter-stub output contract (CounterStubEngine):

      C1 no all-zero stereo sample in the recording (bias +1 guarantees a
         live counter; a stale/silent slot prints zeros and fails),
      C2 the low 12-bit counter field advances by exactly 1 per sample
         within each block (a frozen/repeating slot fails),
      C3 the voice-count nibble is present at block starts where the
         snapshot says voices are active.
    Returns (ok, violations).
    """
    bad = []
    n = len(out_bytes) // 4
    for k in range(n):
        l, r = int.from_bytes(out_bytes[4 * k:4 * k + 2], "little"), \
            int.from_bytes(out_bytes[4 * k + 2:4 * k + 4], "little")
        if l == 0 and r == 0:
            bad.append("C1 all-zero sample at index %d" % k)
            break
    for rec in trace["blocks"]:
        base = rec["b"] * 32
        for i in range(32):
            l = int.from_bytes(out_bytes[4 * (base + i):4 * (base + i) + 2],
                               "little")
            low = l & 0xFFF
            want = (base + i + 1) & 0xFFF
            if low != want:
                bad.append("C2 block %d sample %d: counter field %d != %d"
                           % (rec["b"], i, low, want))
                break
        active = rec["snapshot_after"]["active_count"]
        if active:
            l = int.from_bytes(out_bytes[4 * base:4 * base + 2], "little")
            if (l >> 12) & 0xF != (active & 0xF):
                bad.append("C3 block %d: voice nibble %d != active %d"
                           % (rec["b"], (l >> 12) & 0xF, active & 0xF))
    seen = set()
    uniq = [x for x in bad if not (x.split(":")[0] in seen or seen.add(
        x.split(":")[0]))]
    return (not bad), uniq[:6]


def main():
    iverilog = subprocess.run(["which", "iverilog"], capture_output=True,
                              text=True).returncode == 0
    lines = []
    add = lines.append
    add("SXT-021 negative controls — transcripts (deterministic; generated by")
    add("tools/control_negative_controls.py; every control must FAIL the")
    add("check it targets. iverilog present: %s" % ("yes" if iverilog else
                                                    "no (NC3 NOT_RUN)"))
    add("")
    add("Declared conventions under test: per-block event reserve = 8 "
        "(SXT-016),")
    add("queue depth 16, events quantize UP to the 32-sample block, "
        "v1 hard-switch")
    add("patch change, named stub engine slot. Control plane only — no DSP "
        "claims.")
    add("")

    ok_all = True

    # ---------------------------------------------------------------- NC1
    add("=" * 72)
    add("NC1 (a)  Event burst exceeding the declared reserve -> DETECTED,")
    add("         BOUNDED overload (explicit statuses, never silent)")
    add("=" * 72)

    seq = load_seq("ctl-burst-overload-v1")
    trace, out, summary = render_sequence(seq, CounterStubEngine())
    b0 = trace["blocks"][0]
    add("variant 1: 12 coincident note-ons at t=0 (reserve = 8/block,")
    add("           queue capacity 16 -> no drops possible)")
    add("  block 0 statuses        : %s" % (b0["statuses"],))
    add("  block 0 dispatches      : %d of 12 arrivals (declared reserve)"
        % len(b0["decisions"]))
    add("  spilled decisions       : %s" %
        [(d["seq"], "latency=%dsamples" % d["latency_samples"])
         for r in trace["blocks"][1:3] for d in r["decisions"]])
    add("  drops                   : %d" % summary["drops_total"])
    add("  underruns               : %d (output never stops)" %
        summary["underruns"])
    add("  declared schedule closes: %s (record: "
        "reserve_exceeded_blocks=%d)" %
        ("no" if summary["reserve_exceeded_blocks"] else "yes",
         summary["reserve_exceeded_blocks"]))
    detected = ("event_reserve_exceeded" in b0["statuses"]
                and summary["drops_total"] == 0
                and summary["underruns"] == 0)
    add("  VERDICT: %s" % ("DETECTED (bounded spill, explicit flag, "
                           "accounting refuses to close)"
                          if detected else "NOT DETECTED — CONTROL BROKEN"))
    ok_all &= detected
    add("")

    seq = load_seq("ctl-queue-overflow-v1")
    trace, out, summary = render_sequence(seq, CounterStubEngine())
    b0 = trace["blocks"][0]
    x_lines = 0
    with open(os.path.join(REPO, "fixtures", "control",
                           "ctl-queue-overflow-v1", "rtl_trace.txt")) as f:
        for line in f:
            if line.startswith("X "):
                x_lines += 1
    add("variant 2: 30 coincident note-ons at t=0 (exceeds reserve AND the")
    add("           16-deep queue: queue fills before the block drain)")
    add("  block 0 statuses        : %s" % (b0["statuses"],))
    add("  dropped (model records) : %d explicit queue_overflow records"
        % summary["drops_total"])
    add("  dropped (RTL X records) : %d explicit in-DUT drop records"
        % x_lines)
    add("  first dropped seqs      : %s" %
        [d["seq"] for d in b0["drops"][:4]])
    add("  underruns               : %d (render continues; output never "
        "stops)" % summary["underruns"])
    add("  VERDICT: %s" %
        ("DETECTED (explicit bounded drops in BOTH model and DUT; nothing "
         "silent)" if summary["drops_total"] == x_lines
         and summary["drops_total"] > 0 and "queue_overflow" in b0["statuses"]
         else "NOT DETECTED — CONTROL BROKEN"))
    ok_all &= (summary["drops_total"] == x_lines
               and summary["drops_total"] > 0)
    add("")

    # ---------------------------------------------------------------- NC2
    add("=" * 72)
    add("NC2 (b)  Stub mislabeled as real DSP / stale silent slot ->")
    add("         CAUGHT by the output check (names are not trusted)")
    add("=" * 72)
    seq = load_seq("ctl-notes-steal-v1")
    trace, out, summary = render_sequence(seq, MislabeledRealDspEngine())
    ok, violations = output_check(trace, out)
    add("engine claims : name = %r" % MislabeledRealDspEngine.name)
    add("actual output : all-zero stereo for every sample (dead/stale slot)")
    add("output check  : %s" % ("FAILS as required" if not ok else
                               "PASSED — CONTROL BROKEN"))
    for v in violations:
        add("  violation: %s" % v)
    add("  VERDICT: %s" % ("CAUGHT (a mislabeled or stale stub cannot pass "
                           "the output contract)" if not ok else
                           "NOT CAUGHT — CONTROL BROKEN"))
    ok_all &= (not ok)
    add("")
    add("control: the same check PASSES the declared counter stub "
        "(sanity of the check):")
    trace, out, summary = render_sequence(seq, CounterStubEngine())
    ok_real, v_real = output_check(trace, out)
    add("  counter stub output check: %s (%d violations)" %
        ("PASS" if ok_real else "FAIL", len(v_real)))
    ok_all &= ok_real
    add("")

    # ---------------------------------------------------------------- NC3
    add("=" * 72)
    add("NC3 (c)  RTL-vs-model divergence injected via ONE queue-depth")
    add("         constant (control_broken_mutant.sv: depth 16 -> 15)")
    add("=" * 72)
    if iverilog:
        import tempfile
        import shutil

        def nc3_run(ident, dut_name):
            work = tempfile.mkdtemp(prefix="sxt021-nc3-")
            try:
                return run_comparison(
                    load_seq(ident), work,
                    os.path.join(REPO, "rtl", "control", dut_name))
            finally:
                shutil.rmtree(work, ignore_errors=True)

        # the divergence must be CAUGHT where the queue depth binds
        v = nc3_run("ctl-queue-overflow-v1", "control_broken_mutant.sv")
        add("fixture ctl-queue-overflow-v1 (30 coincident events: the queue")
        add("depth binds) vs mutant:")
        add("  verdict    : %s" % v["verdict"])
        add("  mismatches : %d" % v["mismatches"])
        for f_ in v["first_failures"][:3]:
            add("  divergence : %s" % f_)
        ok_all &= (v["verdict"] == "FAIL")

        # precision note: bursts that never touch the depth do NOT diverge
        v2 = nc3_run("ctl-burst-overload-v1", "control_broken_mutant.sv")
        add("fixture ctl-burst-overload-v1 (12 coincident events: depth "
            "never binds):")
        add("  verdict    : %s (expected: the injected constant is "
            "invisible here — divergence requires a bound to bite)" %
            v2["verdict"])

        add("  VERDICT: %s (comparator fails the mutated queue depth where "
            "it binds)" % ("CAUGHT" if v["verdict"] == "FAIL" else
                           "NOT CAUGHT — CONTROL BROKEN"))
        v_good = nc3_run("ctl-queue-overflow-v1", "control_top.sv")
        add("  sanity     : unmutated DUT on the same fixture = %s "
            "(byte-identical=%s)" % (v_good["verdict"],
                                     v_good["byte_identical_outputs"]))
        ok_all &= (v_good["verdict"] == "PASS")
    else:
        add("  NOT_RUN: iverilog not present; NC3 skipped (never reported "
            "as a pass)")
    add("")
    add("=" * 72)
    add("OVERALL: %s" % ("ALL CONTROLS DEMONSTRABLY FAIL THEIR CHECKS "
                           "(controls healthy)" if ok_all else
                           "A CONTROL PASSED ITS TARGET FAILURE — "
                           "INVESTIGATE (do not ship evidence)"))
    return 0 if ok_all else 1, lines


if __name__ == "__main__":
    os.makedirs(REPORTS, exist_ok=True)
    rc, lines = main()
    transcript = "\n".join(lines) + "\n"
    with open(OUT, "w") as f:
        f.write(transcript)
    print(transcript)
    print("transcript written to %s" % os.path.relpath(OUT, REPO))
    sys.exit(rc)
