#!/usr/bin/env python3
"""SXT-017 stage-2 negative controls (issue #12 acceptance) — live, rerunnable.

Each control names the failure it targets and must demonstrably produce that
failure signal; a control that cannot fail is not a control (AGENTS.md).

  NC-B1  BUDGET SENSITIVITY (issue #12 acceptance item 5). Re-running the
         comparison with a deliberately inflated budget MUST change the
         selected bundle. Run as a LADDER, not a single flip, so the
         comparison's sensitivity is shown to be graded rather than
         accidental.
  NC-B2  A budget-scaled run without --negative-control must REFUSE (exit 2),
         so an inflated run cannot be produced by accident.
  NC-B3  A budget-scaled run targeting reports/sxt-017/ must REFUSE (exit 2),
         so a control artifact can never overwrite the profile result.
  NC-B4  A missing/garbled probe directory must REFUSE (exit 2) rather than
         silently scoring bundles with no cost basis.
  NC-B5  RECORDED FINDING (self-check against overclaiming NC-B1): budget
         inflation alone never turns a bundle fit-claimable, because the
         blocker is unpriced components, not budget. Sensitivity of the
         SELECTION is not sensitivity of the FIT CLAIM.

Writes reports/sxt-017/negative-controls-budget.txt. Deterministic: no
timestamps, fixed scales, fixed inputs.
"""
import io
import json
import sys
import tempfile
from contextlib import redirect_stdout
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from tools import profile_budget  # noqa: E402

OUT_REL = "reports/sxt-017/negative-controls-budget.txt"
SLATE = "reports/sxt-013/candidates/slate-256-balanced.json"
LADDER = (1.0, 2.0, 21.0, 40.0)


def _sanitize(text, tmp):
    """Strip machine-specific paths so the record is byte-deterministic."""
    return (text.replace(str(tmp), "<tmp>")
                .replace(str(REPO), "<repo>"))


def _run(argv, tmp):
    """Run the tool in-process; return (exit_code, stdout, parsed_doc|None)."""
    buf = io.StringIO()
    try:
        with redirect_stdout(buf):
            profile_budget.main(argv)
        code = 0
    except profile_budget.Refuse as e:
        return 2, buf.getvalue() + str(e), None
    except SystemExit as e:  # pragma: no cover - argparse paths
        code = int(e.code or 0)
    doc = None
    out = Path(argv[argv.index("--out") + 1])
    if code == 0 and out.exists():
        doc = json.loads(out.read_text())
    return code, buf.getvalue(), doc


def main():
    lines = []
    w = lines.append
    w("SXT-017 stage-2 (cost-closure) negative controls — live, generated by")
    w("tools/profile_budget_controls.py. Claim scope: SELECTION SENSITIVITY and")
    w("REFUSAL behaviour of tools/profile_budget.py only. No fidelity, support,")
    w("preset-quality, technology, or hardware claim. Profile v1 is NOT frozen.")
    w("=" * 78)
    w("")

    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)

        # -- NC-B1: budget sensitivity ladder --------------------------------
        w("NC-B1 (issue #12 acceptance: inflated budget must change the")
        w("selected bundle) — budget_scale ladder over the same inputs.")
        picks = []
        for k in LADDER:
            argv = ["--slate", SLATE, "--primary-slate", "slate-256-balanced",
                    "--out", str(tmp / ("nc-b1-%g.json" % k))]
            if k != 1.0:
                argv = ["--budget-scale", str(k), "--negative-control"] + argv
            code, out, doc = _run(argv, tmp)
            assert code == 0 and doc is not None, out
            pick = doc["selected_bundle"]
            goal = doc["goal_test"]
            picks.append(pick)
            adm = [b["bundle_id"] for b in doc["bundles"] if b["admissible"]]
            w("  budget_scale %-5g -> selected %-22s admissible %s"
              % (k, repr(pick), adm))
            w("      goal(%s): %d/%d vs threshold %d -> goal_met=%s | "
              "fit_claim=%s"
              % (goal["basis_slate"], goal["predicted_supported"],
                 goal["slate_size"], goal["threshold"], goal["goal_met"],
                 doc["selected_bundle_fit_claim"]))
        distinct = len(set(picks))
        w("  selections across the ladder: %s (%d distinct)"
          % (picks, distinct))
        w("  NC-B1 %s — the selection changes with the budget; the comparison"
          % ("PASS" if distinct > 1 else "FAIL"))
        w("  is sensitive to the budget it is supposed to depend on.")
        w("")

        # -- NC-B2: unacknowledged budget scaling must refuse ----------------
        w("NC-B2 — --budget-scale without --negative-control must REFUSE.")
        code, out, _ = _run(["--budget-scale", "40",
                             "--out", str(tmp / "nc-b2.json")], tmp)
        w("  exit: %d" % code)
        w("  stderr: %s" % _sanitize(out, tmp).strip().splitlines()[-1][:160])
        w("  NC-B2 %s" % ("PASS (control runs cannot be produced by accident)"
                          if code == 2 else "FAIL"))
        w("")

        # -- NC-B3: control artifact must not land in the evidence tree ------
        w("NC-B3 — a --budget-scale run must not write under reports/sxt-017/.")
        code, out, _ = _run(["--budget-scale", "40", "--negative-control",
                             "--out", "reports/sxt-017/cost-closure.json"], tmp)
        w("  exit: %d" % code)
        w("  stderr: %s" % _sanitize(out, tmp).strip().splitlines()[-1][:160])
        w("  NC-B3 %s" % ("PASS (an inflated run can never overwrite the "
                          "profile result)" if code == 2 else "FAIL"))
        w("")

        # -- NC-B4: no cost basis must refuse, never score silently ----------
        w("NC-B4 — a missing probe directory must REFUSE, not score bundles")
        w("with no cost basis at all.")
        code, out, _ = _run(["--probes-dir", str(tmp / "no-such-dir"),
                             "--bundle-id", "B1-core-narrow",
                             "--out", str(tmp / "nc-b4.json")], tmp)
        w("  exit: %d" % code)
        w("  stderr: %s" % _sanitize(out, tmp).strip().splitlines()[-1][:160])
        w("  NC-B4 %s" % ("PASS" if code == 2 else "FAIL"))
        w("")

        # -- NC-B5: recorded finding -----------------------------------------
        w("NC-B5 (recorded finding, self-check against overclaiming NC-B1) —")
        w("budget inflation NEVER produces a fit claim. Across the whole")
        w("ladder every selected bundle carries fit_claim=False, because the")
        w("blocker is UNPRICED components (LFO/envelope/modulation/waveshaper")
        w("cycles and the FX classes no SXT-016 probe covers), not the budget.")
        w("Sensitivity of the SELECTION is not sensitivity of the FIT CLAIM;")
        w("only SXT-023/024/028 pricing work can move the latter.")
        argv = ["--budget-scale", "1000", "--negative-control",
                "--slate", SLATE, "--primary-slate", "slate-256-balanced",
                "--out", str(tmp / "nc-b5.json")]
        code, out, doc = _run(argv, tmp)
        assert code == 0 and doc is not None, out
        w("  budget_scale 1000 -> selected %r fit_claim=%s (still no fit claim)"
          % (doc["selected_bundle"], doc["selected_bundle_fit_claim"]))
        w("  NC-B5 recorded (finding, not a sensitivity failure of NC-B1)")
        w("")

    w("Reproduce: python3 tools/profile_budget_controls.py")
    w("Profile result (budget_scale 1): reports/sxt-017/cost-closure.json")
    text = "\n".join(lines) + "\n"
    (REPO / OUT_REL).write_text(text, encoding="utf-8")
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
