#!/usr/bin/env python3
"""Issue #110 regrade ledger: every committed artifact touched by the shared
`spectral_corr` definition change, with its re-run diff and attribution.

The metric change itself lives in tools/compare_audio_reference.py
(`spectral_corr`, SPECTRAL_CORR_*). The committed artifacts are regenerated by
re-running their OWN producing tools (the runner per report is listed in
reports/spectral-corr-fs-floor/EVIDENCE.md); this script rewrites no
artifact. It compares each committed JSON at the pre-#110 revision
(`--base-rev`) with the working tree and classifies every changed leaf. Where
a leaf also differs from `--rebase-parent-rev` (main's tip when this #110
branch was rebased onto it, before #110's own commit) that leaf is checked
against `--rebase-parent-rev` first: if the working tree already matches it,
the diff from `--base-rev` predates #110 (class REBASE) and is not
re-litigated here.

  SPECTRAL        a `spectral_corr` value (the intended change)
  BUDGET-#110     the boolean result of the spectral_corr >= budget leg
  RMS-FLAG-#95    proposed_budget_results.rms_diff_dbfs moved to the value the
                  corrected (#92) predicate gives on the artifact's own numbers
                  -- a pre-#92 artifact re-emitted by the current tool (#95
                  audit, #97 re-grade); not caused by #110
  VERDICT         a verdict / status / control-ok field; every STATUS change
                  is listed as a flip with its attributed cause
  DEFINITION      the new `spectral_corr_definition` stamp
  ULP             float equal to 1e-12 relative (host float ordering)
  HOST-PATH       a path string that differs only in the host/worktree/scratch
                  prefix
  RE-RENDER       a non-spectral metric of a negative-control artifact whose
                  model render was re-rendered by its leaf runner (the current
                  model on this host); leg 4 of the #110 checks runs the
                  pre-#110 comparator on the same render to show the diff is
                  the render's, not the metric's
  SCHEMA-#100     keys the #100 wet-path tail gate added to a pre-#100 sxt-023
                  record that is now re-emitted by the gated tool
  SCHEMA-#111     the #111 tail-shape (windowed decay-curve) leg: its new
                  `tail_decay_curve`/`decay_curve_*`/`tail_rms_rel_ok`/
                  `tail_decay_curve_ok` fields on an existing record, or a
                  wholesale-new control-list entry (the three late-tail
                  KNOWN-GAP controls #111 added).
  REBASE          a leaf that already differs from --base-rev at
                  --rebase-parent-rev (main as this #110 branch found it,
                  after #111/#108/etc landed, before #110's own commit) AND
                  is byte-identical between --rebase-parent-rev and the
                  working tree: #110 did not touch it, so whatever changed it
                  is main history #110 was rebased onto, not #110 itself (the
                  #108 `tail_window` staleness the #111 tool already disclosed
                  as pre-existing and excludes from its own leg 5 is the
                  concrete case this covers).
  RUN-METADATA    run stamps and the partial-re-run note of a merged summary
  OTHER           anything else -- UNEXPLAINED, fails this script

It also lists every JSON under reports/ that still carries a `spectral_corr`
value and was NOT regenerated, with the reason class, so nothing is silently
left graded under the retired definition.

Exit status: 0 when no artifact has an UNEXPLAINED diff, 1 otherwise.
"""

import argparse
import glob
import json
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "tools"))
BASE_REV = "8ade1d184d1b26f94caa9b3fa3bfbbab2069ff9e"  # pre-#110 main
# main's tip when the #110 branch was rebased onto it (merge of #161: #111's
# tail-shape leg + the #111-change-note SXT-028c re-pin), still pre-#110's own
# commit. A leaf byte-identical between this rev and the working tree was not
# touched by #110; see class REBASE.
REBASE_PARENT_REV = "b2834e998665e33fde805a0332cb5aad3310649e"

# negative-control artifacts whose model render is re-rendered by the leaf's
# own runner (not committed); see spectral_corr_fs_floor_checks.RERENDERS
RERENDER_ARTIFACTS = re.compile(
    r"^reports/(SXT-040/artifacts/nc-|SXT-033/artifacts/nc-|"
    r"sxt-032/artifacts/audio-nc-|sxt-035/artifacts/audio-nc-|"
    r"sxt-035/artifacts/negative-controls\.json|"
    r"SXT-042/artifacts/audio-nc-|SXT-042/artifacts/negative-controls\.json)")
# pre-#100 sxt-023 records re-emitted by the #100-gated fx tool
SCHEMA100_ARTIFACTS = re.compile(
    r"^reports/sxt-023/(artifacts/audio-|artifacts-followup/nc-b/nc-b-)")
SCHEMA100_KEYS = re.compile(
    r"^/(tail_check|tail_check_lr|fixture_sidecar|path|proposed_tail_budget|"
    r"tail_gate_ok)(/|$)")
# #111's tail-shape (windowed decay-curve) leg: new fields on every tail_check
# emitted anywhere (SXT-028c, the shared/stereo tail gates, sxt-023, sxt-024),
# landed on `main` between this ledger's --base-rev and #110's rebase onto it.
SCHEMA111_KEYS = re.compile(
    r"(^|/)(decay_curve_floor_dbfs|decay_curve_max_dev_db|decay_curve_window_s|"
    r"tail_decay_curve_ok|tail_rms_rel_ok)$|"
    r"(^|/)tail_decay_curve(/|$)")
METADATA_KEYS = re.compile(r"(^|/)(run_utc|repo_head|date|numpy)$|"
                           r"^/partial_reruns")

# JSONs that carry spectral_corr values but are NOT graded by the comparators
# changed here (independent per-leaf metric copies, or different budget
# families), or that are historical records. Listed, not rewritten.
NOT_MIGRATED = [
    (r"^reports/sxt-028a/", "NOT-MIGRATED: compare_aw49_reference.py keeps "
     "its own native-unit log1p spectral_corr (float32 bus)"),
    (r"^reports/SXT-028e/", "NOT-MIGRATED: distortion_negative_controls.py "
     "keeps its own log1p spectral_corr (frame 1024, Q10.21 LSB)"),
    (r"^reports/SXT-028e-sse/", "NOT-MIGRATED: distortion-SSE negative "
     "controls keep their own log1p spectral_corr"),
    (r"^reports/SXT-028f/", "NOT-MIGRATED: reverb2_negative_controls.py "
     "keeps its own log1p spectral_corr (integer LSB)"),
    (r"^reports/SXT-039/", "NOT-MIGRATED: compare_lpmoog_model.py L2 leg "
     "(l2_spectral_corr_min 0.999, Q10.21 LSB), a different budget family"),
    (r"^reports/sxt-037/", "NOT-MIGRATED: filter_lp12 L2 leg (0.999, Q10.21 "
     "LSB), a different budget family"),
    (r"^reports/SXT-038/", "NOT-MIGRATED: filter_lp24 L2 leg (0.999), a "
     "different budget family"),
    (r"^reports/SXT-028c/negative-controls/|^reports/sxt-028a/negative-",
     "BUDGET-ONLY: records the spectral_corr_min budget value, no measured "
     "spectral_corr"),
    (r"^reports/halfband-branch-order/", "HISTORICAL: #146 before/after "
     "measurement (no committed producing tool; the b_even renders are not "
     "committed); values are pre-#110 by construction and are not a current "
     "verdict"),
    (r"^reports/stereo-comparator-tail-gate/artifacts/spectral-corr-sweep",
     "HISTORICAL: #100 leg 4 characterization of the LEGACY metric (the "
     "runner now calls spectral_corr_legacy_log1p explicitly)"),
    (r"^reports/tooling-rms-polarity-audit/", "HISTORICAL: #95 audit report"),
    (r"^reports/coverage-v1/", "HISTORICAL: coverage leaf table (quotes "
     "no spectral verdict it grades itself)"),
    (r"^reports/SXT-034/artifacts/(uni2-poly|uni16-smoke)\.json",
     "STALE: reference render retained on the pinned remote oracle, not "
     "committed; cannot be re-graded on this host"),
    (r"^reports/SXT-034/artifacts/nc2-", "STALE: NC-2 mutant inputs were not "
     "committed; a re-construction does not reproduce the committed render "
     "(see EVIDENCE.md)"),
    (r"^reports/sxt-026a/artifacts/audio-smoke-bells-dry\.json",
     "UNCHANGED-BY-DEFINITION: 3904 frames < one 4096 frame; both "
     "definitions give 0.0 for unequal sub-frame renders (reference not "
     "committed)"),
]

VERDICT_KEYS = re.compile(r"(^|/)(verdict|status|ok|all_pass|pass|fail|"
                          r"overall|overall_ok|detected|good|control_ok|"
                          r"result|observed)$")


def git_show(rev, path):
    r = subprocess.run(["git", "show", "%s:%s" % (rev, path)], cwd=REPO,
                       capture_output=True)
    return r.stdout.decode() if r.returncode == 0 else None


def leaves(obj, path=""):
    out = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            out.update(leaves(v, "%s/%s" % (path, k)))
    elif isinstance(obj, list):
        # A list of dict rows carrying a stable "control" name (the #93/#100/
        # #111 controls-list shape) is keyed by that name, not position: #111
        # inserted three new late-tail controls mid-list, and plain positional
        # indexing would misalign every control after the insertion point
        # against a pre-#111 baseline. Duplicate names (e.g. two
        # "refusal/missing-sidecar" rows) are disambiguated by occurrence
        # order, which #111 did not reorder.
        if obj and all(isinstance(x, dict) and "control" in x for x in obj):
            seen = {}
            for v in obj:
                name = v["control"]
                seen[name] = seen.get(name, 0) + 1
                idx = name if seen[name] == 1 else "%s#%d" % (name, seen[name])
                out.update(leaves(v, "%s[%s]" % (path, idx)))
        else:
            for i, v in enumerate(obj):
                out.update(leaves(v, "%s[%d]" % (path, i)))
    else:
        out[path] = obj
    return out


def has_spectral_value(obj):
    return any(k.rsplit("/", 1)[-1] == "spectral_corr"
               and isinstance(v, float) for k, v in leaves(obj).items())


def status_of(v):
    if isinstance(v, bool):
        return v
    if not isinstance(v, str):
        return v
    for s in ("NO_VERDICT", "PASS", "FAIL", "NOT_RUN", "BLOCKED", "STALE",
              "CONTROL-OK", "CONTROL-BROKEN"):
        if v.upper().startswith(s):
            return s
    return v


def _norm_path(s):
    return re.sub(r"[^ ]*/(reports|fixtures|tools|model)/", r"\1/",
                  re.sub(r"/(private/)?tmp/[^ ;]*?/(?=[^/ ]+( |$|;|\)))",
                         "/tmp/<scratch>/", s))


def classify(rel, key, old, new, flat_new, mid_has=False, mid_matches=False):
    last = key.rsplit("/", 1)[-1]
    if last == "spectral_corr_definition":
        return "DEFINITION"
    if METADATA_KEYS.search(key):
        return "RUN-METADATA"
    if key.endswith("proposed_budget_results/spectral_corr") or \
            key.endswith("budget_results/spectral_corr") or \
            re.search(r"spectral_corr>=", key):
        return "BUDGET-#110"
    if key.endswith("proposed_budget_results/rms_diff_dbfs"):
        base = key[: -len("proposed_budget_results/rms_diff_dbfs")]
        val = flat_new.get(base + "rms_diff_dbfs")
        bud = flat_new.get(base + "proposed_budgets/rms_diff_dbfs")
        if isinstance(val, float) and isinstance(bud, (int, float)) and \
                new == (val <= bud):
            return "RMS-FLAG-#95"
    if SCHEMA100_ARTIFACTS.search(rel) and (
            SCHEMA100_KEYS.search(key) or key in ("/ref", "/model")):
        return "SCHEMA-#100"
    if SCHEMA111_KEYS.search(key):
        return "SCHEMA-#111"
    if old == "<absent>" and re.search(r"/controls\[[^\]]+\]/", key):
        # a whole new identity-keyed control-list row (#111's three late-tail
        # KNOWN-GAP controls): every one of its leaves is new against a
        # baseline that predates #111, regardless of the leaf's own name.
        return "SCHEMA-#111"
    if VERDICT_KEYS.search(key) or last.startswith("verdict") or \
            re.search(r"beyond_model_error_via", key):
        return "VERDICT"
    if last == "spectral_corr":
        return "SPECTRAL"
    if isinstance(old, float) and isinstance(new, float) and \
            abs(old - new) <= 1e-12 * max(abs(old), abs(new)):
        return "ULP"
    if isinstance(old, str) and isinstance(new, str) and \
            _norm_path(old) == _norm_path(new):
        return "HOST-PATH"
    if RERENDER_ARTIFACTS.search(rel):
        return "RE-RENDER"
    if mid_has and mid_matches:
        return "REBASE"
    if not mid_has and new == "<absent>":
        # `old` (at --base-rev) had a value under this exact path, and
        # --rebase-parent-rev never had it either: the key was renamed or
        # restructured somewhere in main history between --base-rev and
        # --rebase-parent-rev (e.g. #100's "known_gap_probes" -> #111's
        # "late_tail_controls"), before #110 existed.
        return "REBASE"
    return "OTHER"


def cause_of_flip(changes, lo, ln):
    """Attribute a verdict flip. For the shared comparator's flat shape the
    decisive leg is checked by counterfactual: the new flags with the OLD
    spectral flag must give the old status for #110 to be decisive."""
    pb = "/proposed_budget_results/"
    if pb + "spectral_corr" in lo and pb + "spectral_corr" in ln:
        flags = {k: v for k, v in ln.items() if k.startswith(pb)}
        cf = dict(flags)
        cf[pb + "spectral_corr"] = lo[pb + "spectral_corr"]
        new_ok, cf_ok = all(flags.values()), all(cf.values())
        rms_moved = lo.get(pb + "rms_diff_dbfs") != ln.get(pb + "rms_diff_dbfs")
        if new_ok != cf_ok:
            return ("#110 spectral_corr (decisive: with the old spectral flag "
                    "the verdict would be %s%s)"
                    % ("PASS" if cf_ok else "FAIL",
                       ", even with the #95-corrected rms flag"
                       if rms_moved else ""))
        if rms_moved:
            return "#95 rms-flag correction (the spectral leg is not decisive)"
    classes = {c["class"] for c in changes}
    spec = "BUDGET-#110" in classes or any(
        c["class"] == "VERDICT" and "beyond_model_error" in c["key"]
        for c in changes)
    rms = "RMS-FLAG-#95" in classes
    rer = "RE-RENDER" in classes
    sch = "SCHEMA-#100" in classes
    sch111 = "SCHEMA-#111" in classes
    reb = "REBASE" in classes
    causes = [n for f, n in ((spec, "#110 spectral_corr"),
                             (rms, "#95 rms-flag correction"),
                             (rer, "control re-render"),
                             (sch, "#100 tail gate"),
                             (sch111, "#111 tail-shape leg"),
                             (reb, "pre-existing main history "
                                   "(rebase-parent-rev)")) if f]
    return " + ".join(causes) or "UNATTRIBUTED"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base-rev", default=BASE_REV)
    ap.add_argument("--rebase-parent-rev", default=REBASE_PARENT_REV)
    ap.add_argument("--out-dir", default=os.path.join(
        REPO, "reports", "spectral-corr-fs-floor", "artifacts"))
    args = ap.parse_args()

    lines = []

    def emit(s=""):
        lines.append(s)
        print(s)

    emit("Issue #110 regrade ledger: committed artifacts at pre-#110 %s vs "
         "working tree" % args.base_rev[:12])
    emit("definition: tools/compare_audio_reference.py SPECTRAL_CORR_* "
         "(fs-log-floor-v2, -100 dBFS/bin)")
    emit("")
    changed = set(subprocess.run(
        ["git", "diff", "--name-only", args.base_rev, "--", "reports"],
        cwd=REPO, capture_output=True, text=True).stdout.split())
    regenerated, flips, untouched, unexplained = [], [], [], []
    for p in sorted(glob.glob(os.path.join(REPO, "reports", "**", "*.json"),
                              recursive=True)):
        rel = os.path.relpath(p, REPO)
        if rel.startswith("reports/spectral-corr-fs-floor/"):
            continue
        raw = open(p).read()
        if "spectral_corr" not in raw and rel not in changed:
            continue
        new = json.loads(raw)
        old_src = git_show(args.base_rev, rel) if rel in changed else raw
        if old_src is None:
            continue
        old = json.loads(old_src)
        if not (has_spectral_value(old) or has_spectral_value(new)
                or rel in changed):
            continue
        mid_src = git_show(args.rebase_parent_rev, rel)
        lm = leaves(json.loads(mid_src)) if mid_src is not None else None
        lo, ln = leaves(old), leaves(new)
        changes = []
        for k in sorted(set(lo) | set(ln)):
            a, b = lo.get(k, "<absent>"), ln.get(k, "<absent>")
            if a == b:
                continue
            mid_has = lm is not None and k in lm
            mid_matches = mid_has and lm[k] == b
            c = classify(rel, k, a, b, ln, mid_has, mid_matches)
            if c == "OTHER":
                unexplained.append((rel, k, a, b))
            changes.append({"key": k, "class": c, "old": a, "new": b})
        if changes:
            art_flips = []
            for c in changes:
                if c["class"] == "VERDICT" and c["old"] != "<absent>" and \
                        status_of(c["old"]) != status_of(c["new"]) and \
                        "beyond_model_error_via" not in c["key"]:
                    art_flips.append({"artifact": rel, "key": c["key"],
                                      "old": status_of(c["old"]),
                                      "new": status_of(c["new"])})
            cause = cause_of_flip(changes, lo, ln)
            for f in art_flips:
                f["cause"] = cause
            flips.extend(art_flips)
            counts = {}
            for c in changes:
                counts[c["class"]] = counts.get(c["class"], 0) + 1
            regenerated.append({"artifact": rel, "class_counts": counts,
                                "verdict_flips": art_flips,
                                "changes": changes})
        elif has_spectral_value(new):
            why = next((w for pat, w in NOT_MIGRATED if re.search(pat, rel)),
                       "UNTOUCHED: graded by a migrated comparator but NOT "
                       "regenerated -- must be explained in EVIDENCE.md")
            untouched.append({"artifact": rel, "reason": why})

    emit("REGENERATED (%d artifacts)" % len(regenerated))
    for r in regenerated:
        emit("  %s   [%s]" % (r["artifact"], ", ".join(
            "%s=%d" % kv for kv in sorted(r["class_counts"].items()))))
        for c in r["changes"]:
            if c["class"] == "SPECTRAL":
                emit("      %-13s %-52s %s -> %s"
                     % (c["class"], c["key"][-52:],
                        "%.6f" % c["old"] if isinstance(c["old"], float)
                        else c["old"],
                        "%.6f" % c["new"] if isinstance(c["new"], float)
                        else c["new"]))
            elif c["class"] in ("BUDGET-#110", "VERDICT", "RMS-FLAG-#95",
                                "OTHER"):
                emit("      %-13s %-52s %s -> %s"
                     % (c["class"], c["key"][-52:], str(c["old"])[:48],
                        str(c["new"])[:48]))
    emit("")
    emit("VERDICT / CONTROL-STATUS FLIPS (%d)" % len(flips))
    for f in flips:
        emit("  %s %s: %s -> %s   [cause: %s]"
             % (f["artifact"], f["key"], f["old"], f["new"], f["cause"]))
    emit("")
    emit("CARRY spectral_corr BUT NOT REGENERATED (%d)" % len(untouched))
    for u in untouched:
        emit("  %s -- %s" % (u["artifact"], u["reason"]))
    emit("")
    emit("UNEXPLAINED diffs: %d" % len(unexplained))
    for u in unexplained:
        emit("  %s %s: %r -> %r" % u)

    os.makedirs(args.out_dir, exist_ok=True)
    with open(os.path.join(args.out_dir, "regrade-ledger.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    with open(os.path.join(args.out_dir, "regrade-ledger.json"), "w") as f:
        json.dump({"issue": 110, "base_rev": args.base_rev,
                   "regenerated": regenerated, "verdict_flips": flips,
                   "not_regenerated": untouched,
                   "unexplained": [list(u) for u in unexplained]},
                  f, indent=2)
        f.write("\n")
    return 1 if unexplained else 0


if __name__ == "__main__":
    sys.exit(main())
