#!/usr/bin/env python3
"""Issue #110 checks: the shared full-scale log-floor `spectral_corr`
definition (tools/compare_audio_reference.py SPECTRAL_CORR_*), adopted as a
visible [PROPOSED-TO-BE-FROZEN-AT-PILOT] contract revision and input to the
SXT-017 pilot freeze (#12).

Legs
----
[1] Unit invariance and sensitivity sweep. The #100 perturbation (a
    deterministic ternary +-k native-LSB pattern) on the same four committed
    fixtures (two int16, two stereo float32 mono sums). Reported per row: the
    retired native-unit log1p value, the adopted value, and the residual in
    dBFS. The adopted value depends on the residual level only, not on the
    bus unit. Also records the frame-gating-alone candidate on behemoth (the
    empty-bin case frame gating does not fix).

[2] Floor sensitivity on every committed model-vs-reference pair whose both
    renders are committed (dry int16 pairs discovered by the #93 convention,
    plus the stereo float32 effect-slice pairs). For floors -80 .. -120 dBFS
    per bin, the spectral leg (>= 0.98) is recomputed, so a reviewer can see
    which spectral-leg outcomes depend on the declared -100 dB value. The
    floor was declared in #100 before any case was re-graded; this leg does
    not choose it.

[3] Dry re-run parity against the pre-#110 tool. Every committed dry pair is
    graded by the pre-#110 comparator -- main's, materialized from the BASE
    revision (main as this branch last merged it; see --base-rev) -- and by
    the working tree. The two outputs must be identical except for the fields
    #110 owns: `spectral_corr`, `spectral_corr_definition` (added),
    `proposed_budget_results.spectral_corr`, and `verdict` when (and only
    when) the spectral flag moved. Anything else is UNEXPLAINED and fails the
    leg.

[4] Re-render proof. Negative-control artifacts whose model render is not
    committed were regenerated by re-running their leaf's own runner, which
    re-renders the control model in scratch. For each such render the
    pre-#110 comparator is run on the SAME render: its non-spectral fields
    must equal the regenerated artifact's (so any non-spectral diff against
    the committed artifact comes from the re-render -- the current model on
    this host -- and not from #110). Renders are looked up under
    --renders-root; missing renders make that row NOT_RUN, never a pass.

[5] Tail-gate control legs of #93 (tools/tail_gate_checks.py leg 2) and #100
    (tools/stereo_tail_gate_checks.py leg 2) re-run under the #110 metric;
    their per-control JSONs and transcripts are regenerated and their
    checks-summary.json leg entry is replaced. Every other leg and every
    top-level field is carried byte-identical from the BASE revision's record
    (main's, not an older pinned SHA -- the PR #166 re-review finding), and
    the leg FAILS if the written summary's carried fields differ from it.

[6] Regrade ledger (tools/regrade_spectral_corr.py).

Claim scope: comparator/metric behaviour only. No model-vs-reference fidelity,
RTL, preset-support, or sound claim follows; no budget is frozen here.

Usage:
  python3 tools/spectral_corr_fs_floor_checks.py [--legs 1,2,3,4,5,6]
      [--scratch-root DIR] [--renders-root DIR] [--base-rev REV]
      [--main-ref REF]

The base revision defaults to the merge base of HEAD with origin/main and
is resolved once per run (tools/regrade_spectral_corr.resolve_base_rev),
recorded in checks-summary.json, and passed to the ledger (leg 6).
"""

import argparse
import datetime
import json
import os
import shutil
import subprocess
import sys

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "tools"))

import compare_audio_reference as car  # noqa: E402
import regrade_spectral_corr as rsc  # noqa: E402
import stereo_tail_gate_checks as stg  # noqa: E402
import tail_gate_checks as tgc  # noqa: E402

ART = os.path.join(REPO, "reports", "spectral-corr-fs-floor", "artifacts")
# Resolved once in main() (merge base of HEAD with --main-ref, or --base-rev):
# main as this branch last merged it, i.e. the pre-#110 tree every leg that
# needs "the tool / the record without #110" reads. Never a pinned SHA.
BASE_REV = None
FLOORS = (-80.0, -90.0, -100.0, -110.0, -120.0)
BUDGET = car.PROPOSED["spectral_corr_min"]
OWNED = {"spectral_corr", "spectral_corr_definition"}


def emit(lines, s=""):
    lines.append(s)
    print(s)


def git_show(rev, path):
    r = subprocess.run(["git", "show", "%s:%s" % (rev, path)],
                       capture_output=True, cwd=REPO)
    return r.stdout if r.returncode == 0 else None


def read_mono(path):
    """int16 mono -> (samples, full_scale); stereo f32 -> (mono sum, 1.0)."""
    if tgc._is_mono16(path):
        a, _ = car.read_wav(path)
        return a, car.FULL_SCALE_INT16
    st = stg.read_f32(path).astype(np.float64)
    return 0.5 * (st[0] + st[1]), car.FULL_SCALE_F32


# ---------------------------------------------------------------- leg 1 --

SWEEP_FIXTURES = [
    ("koala2 (int16)", os.path.join(REPO, "fixtures", "audio", "koala2",
                                    "seq-notes-coverage-v1-wet.wav"),
     (1, 4, 16, 64, 256)),
    ("behemoth (int16)", os.path.join(REPO, "fixtures", "audio", "behemoth",
                                      "seq-notes-coverage-v1-wet.wav"),
     (1, 4, 16, 64, 256)),
    ("fmcombo notes (f32 mono sum)",
     os.path.join(REPO, "reports", "SXT-028c", "fixtures",
                  "fmcombo__seq-notes-coverage-v1-wet.f32.wav"),
     (16, 256, 1024, 4096, 16384, 65536)),
    ("alienappears notes (f32 mono sum)",
     os.path.join(REPO, "reports", "SXT-028c", "fixtures",
                  "alienappears__seq-notes-coverage-v1-wet.f32.wav"),
     (16, 256, 1024, 4096, 16384, 65536)),
]


def leg1(lines, scratch):
    emit(lines, "=" * 74)
    emit(lines, "[1] unit invariance / sensitivity sweep (legacy log1p vs "
                "adopted fs-log-floor)")
    emit(lines, "=" * 74)
    emit(lines, "  perturbation: deterministic ternary {-1,0,+1} x k native "
                "LSB everywhere (the #100 pattern)")
    emit(lines, "  native LSB: int16 = 1/32767 FS; f32 = 2^-21 (Q10.21)")
    emit(lines)
    rows = []
    for label, path, ks in SWEEP_FIXTURES:
        ref, fs = read_mono(path)
        unit = 1.0 if fs == car.FULL_SCALE_INT16 else 2.0 ** -21
        pat = stg.pattern(len(ref)).astype(np.float64)
        emit(lines, "  %s: %s" % (label, os.path.relpath(path, REPO)))
        for k in ks:
            mod = ref + pat * k * unit
            d = mod - ref
            r = float(np.sqrt((d * d).mean()))
            row = {"fixture": os.path.relpath(path, REPO), "k_lsb": k,
                   "rms_diff_dbfs": car.rms_dbfs(r, fs),
                   "legacy_native_log1p":
                       car.spectral_corr_legacy_log1p(ref, mod),
                   "adopted": car.spectral_corr(ref, mod, full_scale=fs)}
            rows.append(row)
            emit(lines, "    k=%-6d residual %8.2f dBFS | legacy %.4f %s| "
                        "adopted %.4f %s"
                 % (k, row["rms_diff_dbfs"], row["legacy_native_log1p"],
                    "MISS " if row["legacy_native_log1p"] < BUDGET else "     ",
                    row["adopted"], "MISS" if row["adopted"] < BUDGET else ""))
        emit(lines)
    # unit invariance on real data: the int16 fixture expressed in float FS
    ref, _ = read_mono(SWEEP_FIXTURES[1][1])
    mod = ref + stg.pattern(len(ref)).astype(np.float64)
    inv_i = car.spectral_corr(ref, mod, full_scale=car.FULL_SCALE_INT16)
    inv_f = car.spectral_corr(ref / 32767.0, mod / 32767.0,
                              full_scale=car.FULL_SCALE_F32)
    leg_i = car.spectral_corr_legacy_log1p(ref, mod)
    leg_f = car.spectral_corr_legacy_log1p(ref / 32767.0, mod / 32767.0)
    inv_ok = abs(inv_i - inv_f) < 1e-9
    emit(lines, "  unit invariance, behemoth +-1 LSB expressed on both buses:")
    emit(lines, "    adopted: int16 %.6f | float %.6f -> %s"
         % (inv_i, inv_f, "EQUAL" if inv_ok else "DIFFER"))
    emit(lines, "    legacy : int16 %.6f | float %.6f (unit-bound; the #110 "
                "finding)" % (leg_i, leg_f))
    gated = stg.corr_variant(ref, mod, 32767.0, "gated")
    emit(lines, "  frame gating alone (legacy metric, ref frame >= -80 dBFS) "
                "on behemoth +-1 LSB: %.4f (%s 0.98: gating does not fix the "
                "empty-bin case)" % (gated, "<" if gated < BUDGET else ">="))
    emit(lines)
    ok = inv_ok
    return ok, {"status": "PASS" if ok else "FAIL", "sweep": rows,
                "unit_invariance": {"adopted_int16": inv_i,
                                    "adopted_float": inv_f,
                                    "legacy_int16": leg_i,
                                    "legacy_float": leg_f},
                "frame_gating_alone_behemoth_1lsb": gated}


# ---------------------------------------------------------------- leg 2 --

STEREO_PAIRS = (
    [("SXT-028c", "reports/SXT-028c/fixtures/%s__%s-wet.f32.wav" % (s, q),
      "reports/SXT-028c/artifacts/model__%s__%s.f32.wav" % (s, q))
     for s in ("alienappears", "fmcombo", "fmtwang2")
     for q in ("seq-notes-coverage-v1", "seq-poly-8-v1")]
    + [("sxt-023", "reports/sxt-023/fixtures/%s__seq-notes-coverage-v1-wet"
                   ".f32.wav" % p,
        "reports/sxt-023/artifacts/model__%s__seq-notes-coverage-v1.f32.wav"
        % p) for p in ("dexie", "fm_bass_1", "metallic")]
    + [("sxt-023 nc-b", "reports/sxt-023/fixtures/%s__seq-notes-coverage-v1"
                        "-wet.f32.wav" % p,
        "reports/sxt-023/artifacts-followup/nc-b/ncb__%s__seq-notes-"
        "coverage-v1.f32.wav" % p) for p in ("dexie", "metallic")]
    + [("sxt-025", "reports/sxt-025/fixtures/hells_bells__%s-wet.f32.wav" % q,
        "reports/sxt-025/artifacts/model__%s-wet.f32.wav" % q)
       for q in ("sxt025-smoke-v1", "sxt025-accept-v1")]
    + [("sxt-026a", "reports/sxt-025/fixtures/hells_bells__sxt025-accept-v1"
                    "-wet.f32.wav",
        "reports/sxt-026a/artifacts/model__sxt025-accept-v1-wet.f32.wav")]
)


def committed_pairs():
    cases, skipped = tgc.discover_dry_cases()
    pairs = [(leaf, os.path.relpath(r, REPO), os.path.relpath(m, REPO))
             for leaf, r, m in cases]
    return pairs + [p for p in STEREO_PAIRS
                    if os.path.exists(os.path.join(REPO, p[1]))
                    and os.path.exists(os.path.join(REPO, p[2]))], skipped


def leg2(lines, scratch):
    emit(lines, "=" * 74)
    emit(lines, "[2] floor sensitivity on every committed model-vs-reference "
                "pair (spectral leg >= %.2f)" % BUDGET)
    emit(lines, "=" * 74)
    emit(lines, "  columns: legacy log1p | adopted at floor " +
         " / ".join("%d" % f for f in FLOORS) + " dBFS per bin")
    emit(lines, "  '*' marks a pair whose spectral-leg outcome differs "
                "anywhere in [-110, -90] dBFS")
    emit(lines)
    pairs, skipped = committed_pairs()
    rows = []
    for leaf, rp, mp in pairs:
        ref, fs = read_mono(os.path.join(REPO, rp))
        mod, fs2 = read_mono(os.path.join(REPO, mp))
        assert fs == fs2, (rp, mp)
        n = min(len(ref), len(mod))
        ref, mod = ref[:n], mod[:n]
        legacy = car.spectral_corr_legacy_log1p(ref, mod)
        at = {f: car.spectral_corr(ref, mod, full_scale=fs, floor_db=f)
              for f in FLOORS}
        near = {at[f] >= BUDGET for f in (-110.0, -100.0, -90.0)}
        sensitive = len(near) > 1
        row = {"leaf": leaf, "ref": rp, "model": mp,
               "full_scale": fs, "legacy": legacy,
               "adopted_by_floor": {"%d" % f: v for f, v in at.items()},
               "legacy_leg_pass": legacy >= BUDGET,
               "adopted_leg_pass": at[-100.0] >= BUDGET,
               "floor_sensitive_90_110": sensitive}
        rows.append(row)
        emit(lines, "  %-12s %-50s %.4f | %s %s"
             % (leaf, os.path.basename(mp)[:50], legacy,
                " ".join("%.4f" % at[f] for f in FLOORS),
                "*" if sensitive else ""))
    for leaf, p, why in skipped:
        emit(lines, "  %-12s %-50s NOT_RUN (%s)"
             % (leaf, os.path.basename(p)[:50], why))
    flips = [r for r in rows if r["legacy_leg_pass"] != r["adopted_leg_pass"]]
    sens = [r for r in rows if r["floor_sensitive_90_110"]]
    emit(lines)
    emit(lines, "  pairs graded: %d; spectral-leg outcome moved legacy -> "
                "adopted: %d; floor-sensitive in [-110,-90]: %d"
         % (len(rows), len(flips), len(sens)))
    for r in flips:
        emit(lines, "    moved: %-10s %s  %s -> %s"
             % (r["leaf"], os.path.basename(r["model"]),
                "PASS" if r["legacy_leg_pass"] else "FAIL",
                "PASS" if r["adopted_leg_pass"] else "FAIL"))
    for r in sens:
        emit(lines, "    floor-sensitive: %-10s %s"
             % (r["leaf"], os.path.basename(r["model"])))
    emit(lines)
    return True, {"status": "PASS", "note": "characterization",
                  "floors_dbfs": list(FLOORS), "rows": rows,
                  "not_run": [{"leaf": a, "render": os.path.relpath(b, REPO),
                               "reason": c} for a, b, c in skipped]}


# ---------------------------------------------------------------- leg 3 --

# Repo-relative modules the comparator imports by path (main's
# compare_audio_reference.py puts <repo>/oracle on sys.path for
# oracle_common); materialized alongside it so the base tool runs as it would
# in a checkout of that revision. Absent at a revision -> not materialized.
_MATERIALIZE_DEPS = ("oracle/oracle_common.py",)


def _materialize(rev, rel, scratch, name):
    src = git_show(rev, rel)
    if src is None:
        return None
    root = os.path.join(scratch, "pre110")
    d = os.path.join(root, "tools")
    os.makedirs(d, exist_ok=True)
    p = os.path.join(d, name)
    with open(p, "wb") as f:
        f.write(src)
    for dep in _MATERIALIZE_DEPS:
        dsrc = git_show(rev, dep)
        if dsrc is not None:
            dp = os.path.join(root, dep)
            os.makedirs(os.path.dirname(dp), exist_ok=True)
            with open(dp, "wb") as f:
                f.write(dsrc)
    return p


def owned_diff(base, cur):
    """Keys that differ outside the fields #110 owns (flat dict compare)."""
    fb, fc = stg.flat(base), stg.flat(cur)
    spectral_moved = any(
        k.endswith("proposed_budget_results/spectral_corr")
        and fb.get(k) != fc.get(k) for k in set(fb) | set(fc))
    bad, owned = [], []
    for k in sorted(set(fb) | set(fc)):
        a, b = fb.get(k, "<absent>"), fc.get(k, "<absent>")
        if a == b:
            continue
        leaf = k.rsplit("/", 1)[-1]
        if leaf in OWNED or k.endswith("proposed_budget_results/spectral_corr"):
            owned.append(k)
        elif leaf == "verdict" and spectral_moved:
            owned.append(k)
        else:
            bad.append((k, a, b))
    return owned, bad


def leg3(lines, scratch):
    emit(lines, "=" * 74)
    emit(lines, "[3] dry re-run parity: pre-#110 comparator (main at base %s) "
                "vs working tree" % BASE_REV[:12])
    emit(lines, "=" * 74)
    base_tool = _materialize(BASE_REV, "tools/compare_audio_reference.py",
                             scratch, "compare_audio_reference.py")
    if base_tool is None:
        emit(lines, "  NOT_RUN: pre-#110 tool not available in this clone")
        return False, {"status": "NOT_RUN", "reason": "rev missing"}
    cases, skipped = tgc.discover_dry_cases()
    ok = True
    rows = []
    for leaf, ref, model in cases:
        bj = os.path.join(scratch, "b.json")
        cj = os.path.join(scratch, "c.json")
        rb = tgc.run_tool(base_tool, ref, model, bj)
        rc = tgc.run_tool(tgc.TOOL, ref, model, cj)
        base = json.load(open(bj))
        cur = json.load(open(cj))
        owned, bad = owned_diff(base, cur)
        good = not bad and rb.returncode == rc.returncode
        ok &= good
        rows.append({"leaf": leaf, "ref": os.path.relpath(ref, REPO),
                     "model": os.path.relpath(model, REPO),
                     "owned_diffs": owned,
                     "unexplained": [list(x) for x in bad],
                     "legacy_spectral_corr": base["spectral_corr"],
                     "adopted_spectral_corr": cur["spectral_corr"],
                     "verdict_before": stg.status_of(base["verdict"]),
                     "verdict_after": stg.status_of(cur["verdict"]),
                     "ok": good})
        emit(lines, "  %-10s %-48s %.4f -> %.4f  %s -> %s  %s"
             % (leaf, os.path.basename(ref)[:48], base["spectral_corr"],
                cur["spectral_corr"], stg.status_of(base["verdict"]),
                stg.status_of(cur["verdict"]),
                "OK (only #110 fields differ)" if good
                else "UNEXPLAINED %r" % bad[:3]))
    for leaf, p, why in skipped:
        emit(lines, "  %-10s %-48s NOT_RUN (%s)"
             % (leaf, os.path.basename(p)[:48], why))
    emit(lines, "  leg 3: %s (%d/%d dry cases differ only in #110-owned "
                "fields)" % ("PASS" if ok else "FAIL",
                             sum(1 for r in rows if r["ok"]), len(rows)))
    emit(lines)
    return ok, {"status": "PASS" if ok else "FAIL",
                "base_rev": BASE_REV, "cases": rows,
                "not_run": [{"leaf": a, "render": os.path.relpath(b, REPO),
                             "reason": c} for a, b, c in skipped]}


# ---------------------------------------------------------------- leg 4 --

# (regenerated artifact, reference render, scratch render relative to
#  --renders-root, producing runner) for every negative-control artifact whose
# model render is re-rendered by its leaf runner (not committed).
RERENDERS = (
    [("reports/SXT-040/artifacts/nc-classic-substitution.json",
      "reports/SXT-040/artifacts/badnews__seq-notes-repeated-v1-ref.wav",
      "s040/nc-classic-sub/model.wav", "tools/run_sxt040_checks.py --steps 3"),
     ("reports/SXT-040/artifacts/nc-shape-migration.json",
      "reports/SXT-040/artifacts/tentacles__seq-notes-coverage-v1-ref.wav",
      "s040/nc-shape-raw/model.wav", "tools/run_sxt040_checks.py --steps 3")]
    + [("reports/SXT-033/artifacts/nc-submode-confusion-%s.json" % c,
        "reports/SXT-033/artifacts/%s__seq-notes-repeated-v1-ref.wav" % c,
        "s033/nc-%s/model.wav" % c, "tools/run_sxt033_checks.py --steps 3")
       for c in ("crush", "horn")]
    + [("reports/sxt-032/artifacts/audio-nc-%s.json" % n,
        "reports/sxt-032/artifacts/reference-%s-lfo-fixture.wav" % s,
        "keep/sxt-032/model-%s/model.wav" % n,
        "tools/lfo_negative_controls.py")
       for n, s in (("cutoff-zeroed", "seq-notes-repeated-v1"),
                    ("reso-zeroed", "seq-notes-repeated-v1"),
                    ("source-swap", "seq-modwheel-v1"),
                    ("free-running", "seq-notes-repeated-v1"))]
    + [("reports/sxt-035/artifacts/audio-nc-%s.json" % n,
        "reports/sxt-035/artifacts/reference-seq-modwheel-v1-mw-fixture.wav",
        "keep/sxt-035/model-%s/model.wav" % n,
        "tools/mw_negative_controls.py")
       for n in ("baseline", "cutoff-zeroed", "reso-zeroed", "vca-zeroed",
                 "smoothing-bypass", "source-swap-lfo")]
    + [("reports/SXT-042/artifacts/audio-nc-%s.json" % n,
        "reports/SXT-042/artifacts/reference-sxt025-accept-v1-bells-dry.wav",
        "keep/SXT-042/model-%s/model.wav" % n,
        "tools/kt_negative_controls.py")
       for n in ("baseline", "cutoff-zeroed", "ignore-keytrack-root",
                 "probe-velocity-cutoff-zeroed", "shared-keytrack-word",
                 "source-swap-modwheel", "source-swap-velocity")]
)


def _kt_runner_fields(ref_path, model_path):
    """Fields tools/kt_negative_controls.py adds to the comparator JSON after
    the comparator runs (SXT-042). Recomputed with the runner's own helper on
    the SAME render, so they are proven independent of the metric change."""
    import kt_negative_controls as kt
    return {"windowed_rms_lsb": kt.windowed_rms(kt.read_i16(ref_path),
                                                kt.read_i16(model_path))}


# artifact prefix -> recompute of the fields its runner adds on top of the
# comparator output (absent from the comparator's own JSON by construction)
RUNNER_ADDED = {"reports/SXT-042/artifacts/audio-nc-": _kt_runner_fields}


def _runner_added_check(art, ref_path, model_path, bad):
    """Split `bad` into runner-added keys proven equal on recompute and the
    rest. Returns (still_bad, proven_keys)."""
    fn = next((f for p, f in RUNNER_ADDED.items() if art.startswith(p)), None)
    if fn is None:
        return bad, []
    want = stg.flat(fn(ref_path, model_path))
    still, proven = [], []
    for k, a, b in bad:
        w = want.get(k, "<absent>")
        if a == "<absent>" and isinstance(w, float) and isinstance(b, float) \
                and abs(w - b) <= 1e-12 * max(abs(w), abs(b), 1.0):
            proven.append(k)
        else:
            still.append((k, a, b))
    return still, proven


def leg4(lines, scratch, renders_root):
    emit(lines, "=" * 74)
    emit(lines, "[4] re-render proof: pre-#110 comparator on the SAME "
                "re-rendered control model")
    emit(lines, "=" * 74)
    emit(lines, "  renders root: %s" % renders_root)
    base_tool = _materialize(BASE_REV, "tools/compare_audio_reference.py",
                             scratch, "compare_audio_reference.py")
    ok = True
    rows = []
    for art, ref, rend, runner in RERENDERS:
        mp = os.path.join(renders_root, rend)
        if not os.path.exists(mp) or not os.path.exists(
                os.path.join(REPO, art)):
            rows.append({"artifact": art, "status": "NOT_RUN",
                         "reason": "scratch render not present (re-run %s)"
                         % runner})
            emit(lines, "  %-58s NOT_RUN (render missing)" % art[-58:])
            continue
        bj = os.path.join(scratch, "rr.json")
        tgc.run_tool(base_tool, os.path.join(REPO, ref), mp, bj)
        base = json.load(open(bj))
        regen = json.load(open(os.path.join(REPO, art)))
        committed = json.loads(git_show(BASE_REV, art) or b"{}")
        owned, bad = owned_diff(base, regen)
        bad, proven = _runner_added_check(art, os.path.join(REPO, ref), mp,
                                          bad)
        # drift of the re-render itself, visible under the SAME pre-#110 tool
        _o, drift = owned_diff(committed, base)
        good = not bad
        ok &= good
        rows.append({"artifact": art, "runner": runner, "status":
                     "PASS" if good else "FAIL",
                     "regenerated_vs_pre110_tool_same_render": {
                         "owned": owned, "unexplained": [list(x) for x in bad],
                         "runner_added_recomputed_equal": proven},
                     "rerender_drift_vs_committed_under_pre110_tool":
                         [list(x) for x in drift]})
        emit(lines, "  %-58s %s; re-render drift vs committed (pre-#110 "
                    "tool): %d keys%s"
             % (art[-58:], ("only #110 fields differ" + (
                 " (+%d runner-added keys recomputed equal)" % len(proven)
                 if proven else "")) if good
                else "UNEXPLAINED %r" % bad[:2], len(drift),
                "" if not drift else " e.g. %s" % drift[0][0]))
    # SXT-035 C2 (smoothing-bypass): its "beyond the model's own error"
    # discriminator compares the control against the unmutated baseline on
    # rms and spectral_corr. Same renders, both definitions, all floors.
    disc = {}
    ref_p = os.path.join(REPO, "reports", "sxt-035", "artifacts",
                         "reference-seq-modwheel-v1-mw-fixture.wav")
    paths = {n: os.path.join(renders_root, "keep", "sxt-035",
                             "model-%s" % n, "model.wav")
             for n in ("baseline", "smoothing-bypass")}
    if all(os.path.exists(p) for p in paths.values()):
        ref, _ = car.read_wav(ref_p)
        for n, p in paths.items():
            m, _ = car.read_wav(p)
            k = min(len(ref), len(m))
            disc[n] = {"legacy": car.spectral_corr_legacy_log1p(ref[:k],
                                                                m[:k]),
                       "rms_diff_lsb": float(np.sqrt(((ref[:k] - m[:k]) ** 2)
                                                     .mean()))}
            for f in FLOORS:
                disc[n]["adopted_%d" % f] = car.spectral_corr(
                    ref[:k], m[:k], full_scale=car.FULL_SCALE_INT16,
                    floor_db=f)
        b, c = disc["baseline"], disc["smoothing-bypass"]
        emit(lines, "  SXT-035 C2 smoothing-bypass discriminator (control must "
                    "be WORSE than the unmutated baseline on rms or spectral):")
        emit(lines, "    rms_diff_lsb: baseline %.1f, control %.1f -> control "
                    "%s" % (b["rms_diff_lsb"], c["rms_diff_lsb"],
                            "worse" if c["rms_diff_lsb"] > b["rms_diff_lsb"]
                            else "NOT worse"))
        for key in ["legacy"] + ["adopted_%d" % f for f in FLOORS]:
            emit(lines, "    spectral %-12s baseline %.4f, control %.4f -> "
                        "control %s" % (key, b[key], c[key],
                                        "worse" if c[key] < b[key]
                                        else "NOT worse"))
        worse_at = [f for f in FLOORS
                    if c["adopted_%d" % f] < b["adopted_%d" % f]]
        emit(lines, "    => spectral discriminates under: legacy=%s; adopted "
                    "floors %s dBFS; at the declared -100 dBFS: %s"
             % (c["legacy"] < b["legacy"],
                [int(f) for f in worse_at] or "none",
                "YES" if -100.0 in worse_at else "NO (control-status finding)"))
    else:
        emit(lines, "  SXT-035 C2 discriminator: NOT_RUN (renders missing)")
    emit(lines, "  leg 4: %s" % ("PASS" if ok else "FAIL"))
    emit(lines)
    return ok, {"status": "PASS" if ok else "FAIL", "rows": rows,
                "sxt035_c2_discriminator": disc or "NOT_RUN"}


# ---------------------------------------------------------------- leg 5 --

# top-level keys a merged summary may legitimately change: the partial-re-run
# note this leg appends, and `overall`, recomputed over the legs. Everything
# else -- every carried leg, run_utc/repo_head of the original run,
# amended_by_issue, proposed_tail_budget, ... -- must equal the base record.
MERGE_OWNED_TOP = ("legs", "partial_reruns", "overall")


def carried_mismatches(record, base_record, rerun_legs):
    """Keys of a merged tail-gate summary that were supposed to be carried
    from `base_record` unchanged but differ: every top-level key outside
    MERGE_OWNED_TOP, and every leg not in `rerun_legs`. [] means the merge
    carried the base faithfully. Used by leg 5 on its own output and by
    tests/test_spectral_corr_fs_floor.py."""
    bad = []
    for k in sorted(set(record) | set(base_record)):
        if k in MERGE_OWNED_TOP:
            continue
        if record.get(k, "<absent>") != base_record.get(k, "<absent>"):
            bad.append(k)
    rl, bl = record.get("legs", {}), base_record.get("legs", {})
    for k in sorted(set(rl) | set(bl)):
        if k in rerun_legs:
            continue
        if rl.get(k, "<absent>") != bl.get(k, "<absent>"):
            bad.append("legs/" + k)
    return bad


def merge_summary_record(base_record, issue_key, leg_key, rep, stamp, head,
                         leg_desc):
    """The merged summary: `base_record` (main's record at BASE_REV) with
    only `leg_key` replaced, a #110 partial-re-run note appended, and
    `overall` recomputed. Pure, so a test can build one from any record."""
    old = json.loads(json.dumps(base_record))
    old["legs"][leg_key] = {kk: vv for kk, vv in rep.items()
                            if kk != "sweep"}
    notes = old.setdefault("partial_reruns", [])
    notes.append({"issue": 110, "run_utc": stamp, "repo_head": head,
                  "legs_rerun": [leg_key],
                  "note": "%s re-run under the #110 spectral_corr definition; "
                          "every other leg entry is carried unchanged from "
                          "the %s record (see reports/spectral-corr-fs-floor/"
                          "EVIDENCE.md)" % (leg_desc, issue_key)})
    old["overall"] = ("PASS" if all(
        v.get("status") in ("PASS",) for v in old["legs"].values())
        else "FAIL")
    return old


def _merge_summary(path, issue_key, leg_key, rep, stamp, head, leg_desc):
    """Replace one leg of a committed tail-gate summary. The starting record
    is main's at BASE_REV -- the record this branch merges into -- so every
    carried leg and header field stays what main has, and re-running this
    leg is idempotent. (It used to start from a pinned pre-#111 SHA, which
    silently reverted #111's legs once main moved on: PR #166 re-review.)
    No base record is a hard failure, never a fallback to the working tree.
    Returns carried_mismatches() of what was written ([] = faithful)."""
    rel = os.path.relpath(path, REPO)
    base = git_show(BASE_REV, rel)
    if base is None:
        raise SystemExit("no %s at base %s: cannot carry its legs"
                         % (rel, BASE_REV[:12]))
    base_record = json.loads(base)
    merged = merge_summary_record(base_record, issue_key, leg_key, rep,
                                  stamp, head, leg_desc)
    with open(path, "w") as f:
        json.dump(merged, f, indent=2)
        f.write("\n")
    return carried_mismatches(json.load(open(path)), base_record, (leg_key,))


def leg5(lines, scratch, stamp, head):
    emit(lines, "=" * 74)
    emit(lines, "[5] tail-gate control legs of #93 and #100 re-run under the "
                "#110 metric")
    emit(lines, "=" * 74)
    ok = True
    rep = {}
    # #93 leg 2
    l93 = ["issue #93 -- shared-comparator wet-path tail gate: checks",
           "run: %s   repo HEAD: %s" % (stamp, head),
           "tool: tools/compare_audio_reference.py",
           "re-run: leg 2 only, by issue #110 (spectral_corr definition "
           "change); leg 1 is carried",
           "claim scope: comparator behaviour only. No model-vs-reference, "
           "RTL, preset-support,",
           "             or sound-quality claim follows from anything below.",
           ""]
    # the #93/#100 runners' own default scratch roots, so refusal texts that
    # quote a scratch path stay byte-identical to their records
    s93 = "/tmp/sxt-tail-gate-checks"
    shutil.rmtree(s93, ignore_errors=True)
    os.makedirs(s93)
    good, r93 = tgc.leg2(l93, s93)
    l93.append("leg 2 verdict: %s" % r93["status"])
    with open(os.path.join(tgc.ART, "negative-controls.txt"), "w") as f:
        f.write("\n".join(l93) + "\n")
    drift93 = _merge_summary(os.path.join(tgc.ART, "checks-summary.json"),
                             "#93", "wet_tail_controls", r93, stamp, head,
                             "leg 2")
    ok &= good and not drift93
    rep["issue93_leg2"] = r93["status"]
    rep["issue93_carried_mismatches"] = drift93
    emit(lines, "  #93 leg 2 (shared int16 tail-gate controls): %s"
         % r93["status"])
    for c in r93["controls"]:
        emit(lines, "    %-30s expect %-6s got %-6s %s"
             % (c["control"], c["expect"], c["got"],
                "OK" if c["as_required"] else "WRONG"))
    # #100 leg 2
    s100 = "/tmp/sxt-stereo-tail-gate"
    shutil.rmtree(s100, ignore_errors=True)
    os.makedirs(s100)
    l100 = ["issue #100 -- stereo comparator tail gate / metric findings: "
            "leg 2",
            "run: %s   repo HEAD: %s   numpy %s" % (stamp, head,
                                                    np.__version__),
            "re-run by issue #110 (spectral_corr definition change); legs "
            "1, 3, 4, 5 are carried",
            "claim scope: comparator behaviour only; no fidelity, support, or "
            "sound claim.",
            # the same #111 amendment line stereo_tail_gate_checks.main()
            # writes on every leg transcript (dropped by the first #110 run)
            "amended by issue #111: tail gate now carries the tail-shape "
            "(decay-curve) leg; budget %s" % json.dumps(car.PROPOSED_TAIL,
                                                         sort_keys=True),
            ""]
    good, r100 = stg.leg2(l100, s100)
    l100.append("")
    l100.append("leg 2 verdict: %s" % r100["status"])
    with open(os.path.join(stg.ART, "negative-controls.txt"), "w") as f:
        f.write("\n".join(l100) + "\n")
    drift100 = _merge_summary(os.path.join(stg.ART, "checks-summary.json"),
                              "#100", "stereo_tail_controls", r100, stamp,
                              head, "leg 2")
    ok &= good and not drift100
    rep["issue100_leg2"] = r100["status"]
    rep["issue100_carried_mismatches"] = drift100
    emit(lines, "  #100 leg 2 (stereo tail-gate controls): %s"
         % r100["status"])
    emit(lines, "  carried from main's records at base %s: #93 summary %s; "
                "#100 summary %s" % (BASE_REV[:12],
                                     "byte-identical" if not drift93
                                     else "DRIFT %s" % drift93,
                                     "byte-identical" if not drift100
                                     else "DRIFT %s" % drift100))
    for c in r100["controls"]:
        emit(lines, "    %-40s required %-10s observed %-10s %s"
             % (c["control"], c["required"], c["observed"], c["result"]))
    emit(lines)
    return ok, {"status": "PASS" if ok else "FAIL", **rep}


# ---------------------------------------------------------------- leg 6 --

def leg6(lines, scratch):
    emit(lines, "=" * 74)
    emit(lines, "[6] regrade ledger (tools/regrade_spectral_corr.py)")
    emit(lines, "=" * 74)
    r = subprocess.run([sys.executable, os.path.join(REPO, "tools",
                                                     "regrade_spectral_corr.py"),
                        "--out-dir", ART, "--base-rev", BASE_REV],
                       capture_output=True, text=True,
                       cwd=REPO)
    tail = [ln for ln in r.stdout.splitlines()
            if ln.startswith(("REGENERATED", "VERDICT FLIPS",
                              "CARRY", "UNEXPLAINED"))]
    for ln in tail:
        emit(lines, "  " + ln)
    emit(lines, "  full ledger: reports/spectral-corr-fs-floor/artifacts/"
                "regrade-ledger.{txt,json}")
    emit(lines)
    ok = r.returncode == 0
    return ok, {"status": "PASS" if ok else "FAIL",
                "ledger": "reports/spectral-corr-fs-floor/artifacts/"
                          "regrade-ledger.json"}


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--legs", default="1,2,3,4,5,6")
    ap.add_argument("--scratch-root", default="/tmp/sxt-spectral-corr-110")
    ap.add_argument("--renders-root", default="/tmp/sxt110",
                    help="root of the scratch control re-renders (leg 4)")
    ap.add_argument("--base-rev", default=None,
                    help="pre-#110 main to attribute against (default: the "
                         "merge base of HEAD with --main-ref)")
    ap.add_argument("--main-ref", default=rsc.MAIN_REF)
    args = ap.parse_args()
    global BASE_REV
    BASE_REV = rsc.resolve_base_rev(args.base_rev, args.main_ref)
    legs = {int(x) for x in args.legs.split(",") if x.strip()}
    if os.path.exists(args.scratch_root):
        shutil.rmtree(args.scratch_root)
    os.makedirs(args.scratch_root)
    os.makedirs(ART, exist_ok=True)
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ")
    head = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True,
                          text=True, cwd=REPO).stdout.strip()
    names = {1: ("unit_sweep", "unit-sweep", leg1),
             2: ("floor_sensitivity", "floor-sensitivity", leg2),
             3: ("dry_parity_vs_pre110", "dry-parity", leg3),
             4: ("rerender_proof", "rerender-proof", leg4),
             5: ("tail_gate_controls_rerun", "tail-gate-controls", leg5),
             6: ("regrade_ledger", "regrade-ledger-run", leg6)}
    summary_path = os.path.join(ART, "checks-summary.json")
    summary = (json.load(open(summary_path)) if os.path.exists(summary_path)
               else {"issue": 110, "legs": {}})
    summary.update({"issue": 110, "run_utc": stamp, "repo_head": head,
                    "base_rev": BASE_REV,
                    "numpy": np.__version__,
                    "definition": car.SPECTRAL_CORR_DEFINITION,
                    "floor_db": car.SPECTRAL_CORR_FLOOR_DB})
    ok = True
    for leg in sorted(legs):
        key, fname, fn = names[leg]
        lines = ["issue #110 -- shared full-scale log-floor spectral_corr: "
                 "leg %d" % leg,
                 "run: %s   repo HEAD: %s   numpy %s"
                 % (stamp, head, np.__version__),
                 "definition: %s" % car.SPECTRAL_CORR_DEFINITION,
                 "claim scope: metric/comparator behaviour only; no fidelity, "
                 "support, RTL or sound claim.", ""]
        scratch = os.path.join(args.scratch_root, "leg%d" % leg)
        os.makedirs(scratch, exist_ok=True)
        if leg == 4:
            good, rep = fn(lines, scratch, args.renders_root)
        elif leg == 5:
            good, rep = fn(lines, scratch, stamp, head)
        else:
            good, rep = fn(lines, scratch)
        ok &= good
        lines.append("leg %d verdict: %s" % (leg, rep["status"]))
        with open(os.path.join(ART, fname + ".txt"), "w") as f:
            f.write("\n".join(lines) + "\n")
        if leg in (1, 2, 3, 4):
            with open(os.path.join(ART, fname + ".json"), "w") as f:
                json.dump(rep, f, indent=2)
                f.write("\n")
        summary["legs"][key] = {k: v for k, v in rep.items()
                                if k in ("status", "reason", "note",
                                         "issue93_leg2", "issue100_leg2",
                                         "issue93_carried_mismatches",
                                         "issue100_carried_mismatches",
                                         "ledger", "base_rev")}
    summary["overall"] = ("PASS" if all(v.get("status") == "PASS"
                                        for v in summary["legs"].values())
                          else "FAIL")
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)
        f.write("\n")
    print("OVERALL: %s" % summary["overall"])
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
