"""SXT-028b frozen fixed-point model of the Surge XT Conditioner effect.

Structure authority (READ, cited; GPL-3.0-or-later trees pinned at
surge-synthesizer/surge@58914e59c608ed4384ba6002e44c3465c58b2e71 and its
submodules per oracle/manifest.json -- no code or tables copied):

  src/common/dsp/effects/ConditionerEffect.{h,cpp}
      ctor, init(), setvars(), process(), process_only_control(),
      suspend() (== init()), get_ringout_decay() == 100.
  src/common/dsp/Effect.{h,cpp}
      Effect::Effect sets ringout = 10000000; Effect::process_ringout
      (ringout counter; process() while ringout < decay, otherwise
      process_only_control()).
  src/common/SurgeSynthesizer.cpp / SurgeSynthesizerIO.cpp
      patch load -> loadFx(false, true): every FX slot is RE-SPAWNED (fresh
      object) and init()ed; stopSound() -> fx->suspend() on every slot.
  libs/sst/sst-filters BiquadFilter.h (e92d93a9...): calc_omega,
      coeff_peakEQ -> coeff_orfanidisEQ, coeff_HP, set_coef first_run
      startValue semantics, mono process_block(float*) uses the channel-0
      registers only, suspend() clears registers + first_run (NOT called by
      ConditionerEffect::init()).
  libs/sst/sst-basic-blocks MidSide.h (a32b8aec...): encodeMS M=0.5(L+R),
      S=0.5(L-R); decodeMS L=M+S, R=M-S.
  src/common/dsp/vembertech/lipol.h: lipol_ps_blocksz =
      lipol_sse<BLOCK_SIZE, false> (same ramp class as Delay/Chorus; the
      shared delay_model.Lipol is reused unchanged).
  libs/sst/sst-basic-blocks mechanics/simd-ops.h: mech::rcp (SSE approximate
      reciprocal) -- see "Declared deviations".

Citation correction (recorded, not silently absorbed): the issue title and
scope line (generated by tools/generate_effect_leaves.py) describe
"gate/compressor/LFO" and "process_block; gate/comp envelope lag objects;
shared LFO". The pinned source has NO gate and NO LFO of any kind; the entry
point is process(dataL, dataR); the declared `lipol<float,true> a_rate,
r_rate` members are never referenced in ConditionerEffect.cpp (dead state).
The real algorithm: fixed-frequency bass/treble peaking EQ -> M/S encode ->
side-channel high-pass -> width -> M/S decode -> balance/threshold pregain ->
128-sample look-ahead limiter/compressor (squared-peak detector, attack/
release one-poles, reciprocal gain) -> output gain. The pinned SOURCE, not
the issue prose, is the algorithm authority (AGENTS.md).

The dead reduction tree: process() reads `la = lamax[lookahead - 2]`, i.e.
the FIXED leaf slot 126, while also building a 7-level max tree into
lamax[128..254] every sample. No tree node is ever read (the only lamax
readers are the fixed read and the tree's own level-0 reads of leaves), so
the tree cannot affect any output; it is not modeled. The observable
consequence is load-bearing: the detector sees the squared peak of ONE
sample per 128 (the sample written when bufpos == 126), held for 128
samples.

Frozen word formats (model/effects/README.md conventions, reused
unchanged): audio Q10.21 s32; lipol ramps Q13.18 s32; biquad
coefficients/lags/TDF2 state, attack/release coefficients, squared-peak
leaves, envelope trackers and gain Q24.43 s64. Exact products, round-half-
up, saturating (qmath.py); no floating point at audio run time.

Declared deviations (bounded; absorbed by model-vs-reference budgets once
SXT-017/#12 freezes them -- NONE of these is measured on this host, the
reference leg is BLOCKED):
  * engine float32 audio/state arithmetic -> Q10.21/Q13.18/Q24.43;
  * mech::rcp (SSE _mm_rcp_ps, ~12-bit relative accuracy) -> exact
    round-half-up fixed-point reciprocal (qmath.qdiv). The engine's
    process_only_control() uses an exact 1.f/x, process() uses rcp; the
    model uses the exact form for both. LARGEST declared deviation of this
    leaf: at unity gain rcp(1.0) is not guaranteed to be exactly 1.0, so
    even the uncompressed path may carry a ~2^-12 relative gain offset in
    the engine. MUST be measured (or rcp reproduced bit-exactly) before any
    reference budget for this leaf freezes;
  * sqrtf(2*la) -> exact integer square root of the Q24.43 word;
  * M/S halving: exact in float, sign-correct truncation toward zero here
    (<= 1/2 LSB, same convention as the landed Chorus width step);
  * db_to_linear / calc_omega / coeff_* evaluated in double at control rate,
    quantized once (same declared class as every landed effect model);
  * flush_denormal on the biquad registers is not modeled (fixed point has
    no denormals);
  * parameter modulation INTO conditioner parameters is outside the frozen
    scope (fail-closed; extraction refuses such presets).

The block-constant attack/release coefficients are computed with an EXACT
float32 emulation of the engine's float chain (`1.0f + 0.9f * x`,
`0.001f * am * am`, `0.0001f * rm * rm`), then quantized to Q24.43 once.
"""

import hashlib
import math
import os
import struct as _struct
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))))

from model.effects.qmath import (  # noqa: E402
    FRAC, sat, qadd, qsub, qmul, qdiv, to_q,
)
from model.effects.delay.delay_model import (  # noqa: E402
    Biquad, Lipol, db_to_linear_d, note_to_pitch_ignoring_tuning_d,
    A_FMT, G_FMT, C_FMT, BLOCK,
)

A_FRAC = FRAC[A_FMT]
G_FRAC = FRAC[G_FMT]
C_FRAC = FRAC[C_FMT]

LOOKAHEAD_BITS = 7                      # ConditionerEffect.h lookahead_bits
LOOKAHEAD = 1 << LOOKAHEAD_BITS         # 128 samples = 2.667 ms @ 48 kHz
LOOKAHEAD_MASK = LOOKAHEAD - 1
LA_READ_INDEX = LOOKAHEAD - 2           # fixed leaf slot 126 (see docstring)
RINGOUT_DECAY_BLOCKS = 100              # ConditionerEffect::get_ringout_decay()
RINGOUT_INIT = 10000000                 # Effect::Effect ringout
# process() blocks the engine still runs after the last input-present block:
# ringout = 1..99 -> process(); ringout = 100 -> process_only_control().
TAIL_PROCESS_BLOCKS = RINGOUT_DECAY_BLOCKS - 1
TAIL_SPAN_SAMPLES = TAIL_PROCESS_BLOCKS * BLOCK   # 3,168 samples = 66 ms

ONE_C = 1 << C_FRAC                     # 1.0 in Q24.43
SAMPLE_RATE = 48000.0

_BASS_SCFREQ = -2.5                      # band1.calc_omega(-2.5)
_TREBLE_SCFREQ = 4.75                    # band2.calc_omega(4.75)
_EQ_BW = 2.0                             # coeff_peakEQ(..., 2, gain)
_HP_Q = 0.4                              # hp.coeff_HP(..., 0.4)

# control-word flag bits (declared model -> RTL boundary)
FLAG_BASS_ON = 1 << 0
FLAG_TREBLE_ON = 1 << 1
FLAG_HP_ON = 1 << 2
FLAG_CONTROL_ONLY = 1 << 3     # this block ran process_only_control()
FLAG_SUSPEND = 1 << 4          # engine suspend() (== init()) before block
FLAG_FRESH = 1 << 5            # fresh spawn + init() (patch load) before block
CTRL_WORDS = 22                # attack, release, 4 lipol raws, 15 bq tgts, flags


def f32(x):
    """Round a Python float to IEEE-754 binary32 (round-to-nearest-even)."""
    return _struct.unpack("f", _struct.pack("f", x))[0]


def attack_release_f32(attack_f, release_f):
    """Exact float32 emulation of process()'s coefficient chain.

    float am = 1.0f + 0.9f * a;  float rm = 1.0f + 0.9f * r;
    float attack = 0.001f * am * am;  float release = 0.0001f * rm * rm;
    Each binary32 product/sum of binary32 operands is exact in double here
    (<= 48 significant bits) before the single f32() rounding, so this is
    the IEEE float32 result, not an approximation of it.
    """
    a = f32(attack_f)
    r = f32(release_f)
    am = f32(1.0 + f32(f32(0.9) * a))
    rm = f32(1.0 + f32(f32(0.9) * r))
    attack = f32(f32(f32(0.001) * am) * am)
    release = f32(f32(f32(0.0001) * rm) * rm)
    return attack, release


def calc_omega_d(scfreq):
    """BiquadFilter::calc_omega: 2*pi*440*n2p((float)(12*scfreq))/sr."""
    return 2.0 * math.pi * 440.0 * \
        note_to_pitch_ignoring_tuning_d(f32(12.0 * scfreq)) / SAMPLE_RATE


def _norm(a0, a1, a2, b0, b1, b2):
    inv = 1.0 / a0
    return [to_q(a1 * inv, C_FMT), to_q(a2 * inv, C_FMT), to_q(b0 * inv, C_FMT),
            to_q(b1 * inv, C_FMT), to_q(b2 * inv, C_FMT)]


def coeff_hp(omega, q):
    """BiquadFilter::coeff_HP."""
    if omega > math.pi:
        return _norm(1, 0, 0, 0, 0, 0)
    cosi, sinu = math.cos(omega), math.sin(omega)
    alpha = sinu / (2.0 * q)
    return _norm(1 + alpha, -2 * cosi, 1 - alpha,
                 (1 + cosi) * 0.5, -(1 + cosi), (1 + cosi) * 0.5)


def coeff_peak_eq(omega, bw, gain_db):
    """BiquadFilter::coeff_peakEQ -> coeff_orfanidisEQ(w, BW, G, GB, G0=1)."""
    g0 = 1.0
    g = db_to_linear_d(gain_db)
    gb = db_to_linear_d(gain_db * 0.5)
    w0 = omega
    bw = max(0.0001, bw)
    dww = 2.0 * w0 * math.sinh((math.log(2.0) / 2.0) * bw)
    if not abs(g - g0) > 0.00001:
        return _norm(1, 0, 0, 1, 0, 0)
    f = abs(g * g - gb * gb)
    g00 = abs(g * g - g0 * g0)
    f00 = abs(gb * gb - g0 * g0)
    pi2 = math.pi * math.pi
    num = g0 * g0 * (w0 * w0 - pi2) ** 2 + g * g * f00 * pi2 * dww * dww / f
    den = (w0 * w0 - pi2) ** 2 + f00 * pi2 * dww * dww / f
    g1 = math.sqrt(num / den)
    if omega > math.pi:
        g = g1 * 0.9999
        w0 = math.pi - 0.00001
        g00 = abs(g * g - g0 * g0)
        f00 = abs(gb * gb - g0 * g0)
    g01 = abs(g * g - g0 * g1)
    g11 = abs(g * g - g1 * g1)
    f01 = abs(gb * gb - g0 * g1)
    f11 = abs(gb * gb - g1 * g1)
    w2 = math.sqrt(g11 / g00) * math.tan(w0 / 2.0) ** 2
    w_lower = w0 * f32(2.0 ** (-0.5 * bw))           # powf(2, -0.5*BW)
    w_upper = 2.0 * math.atan(math.sqrt(f00 / f11) * math.sqrt(g11 / g00) *
                              math.tan(w0 / 2.0) ** 2 / math.tan(w_lower / 2.0))
    dw = abs(w_upper - w_lower)
    dW = (1.0 + math.sqrt(f00 / f11) * w2) * math.tan(dw / 2.0)
    c = f11 * dW * dW - 2.0 * w2 * (f01 - math.sqrt(f00 * f11))
    d = 2.0 * w2 * (g01 - math.sqrt(g00 * g11))
    a = math.sqrt((c + d) / f)
    b = math.sqrt((g * g * c + gb * gb * d) / f)
    return _norm(1 + w2 + a, -2 * (1 - w2), 1 + w2 - a,
                 g1 + g0 * w2 + b, -2 * (g1 - g0 * w2), g1 - b + g0 * w2)


def isqrt_c(x_c):
    """Exact Q24.43 square root: floor(sqrt(x_c * 2^43)), x_c >= 0.

    A shift/compare (digit-by-digit) integer square root is a standard
    synthesizable block; nothing is copied from the engine (float32 sqrtf).
    """
    if x_c <= 0:
        return 0
    return sat(math.isqrt(x_c << C_FRAC), C_FMT)


def half_toward_zero(v):
    return v >> 1 if v >= 0 else -((-v) >> 1)


class ConditionerParams:
    """Frozen control-plane inputs for one Conditioner instance (native-
    loader-normalized values; ConditionerEffect.h cond_params order:
    bass(0) treble(1) width(2) balance(3) threshold(4) attack(5) release(6)
    gain(7) hpwidth(8))."""

    FIELDS = ("bass_db", "treble_db", "width_f", "balance_f", "threshold_db",
              "attack_f", "release_f", "gain_db", "hpwidth_semitones")

    def __init__(self, d):
        for k in self.FIELDS:
            setattr(self, k, float(d[k]))
        self.bass_deactivated = bool(d.get("bass_deactivated", False))
        self.treble_deactivated = bool(d.get("treble_deactivated", False))
        # init_default_values / handleStreamingMismatches(rev <= 16):
        # hpwidth defaults to -60 and DEACTIVATED
        self.hpwidth_deactivated = bool(d.get("hpwidth_deactivated", True))

    def as_dict(self):
        d = {k: getattr(self, k) for k in self.FIELDS}
        d.update(bass_deactivated=self.bass_deactivated,
                 treble_deactivated=self.treble_deactivated,
                 hpwidth_deactivated=self.hpwidth_deactivated)
        return d


class ConditionerState:
    """Per-instance Conditioner state. Two slots = two of these, never
    shared (AGENTS.md)."""

    def __init__(self, name="conditioner"):
        self.name = name
        self.band1 = Biquad()
        self.band2 = Biquad()
        self.hp = Biquad()
        self.ampL = Lipol()
        self.ampR = Lipol()
        self.width_s = Lipol()
        self.postamp = Lipol()
        self.ringout = RINGOUT_INIT
        self.clear_limiter()

    def clear_limiter(self):
        """The part of init() that touches limiter state."""
        self.delayed = [[0] * LOOKAHEAD, [0] * LOOKAHEAD]   # [L,R] Q10.21
        self.lamax = [0] * LOOKAHEAD                        # leaves, Q24.43
        self.bufpos = 0
        self.filtered_lamax = ONE_C
        self.filtered_lamax2 = ONE_C
        self.gain = ONE_C
        self.ring_hash = 0
        self.state_reads = 0
        self.state_writes = 0

    def checkpoint(self):
        """Declared per-block checkpoint (compared with the RTL exactly)."""
        d = {"bufpos": self.bufpos,
             "flamax": self.filtered_lamax, "flamax2": self.filtered_lamax2,
             "gain": self.gain,
             "ampL": self.ampL.current, "ampLb": self.ampL.target,
             "ampR": self.ampR.current, "ampRb": self.ampR.target,
             "wid": self.width_s.current, "widb": self.width_s.target,
             "pa": self.postamp.current, "pab": self.postamp.target}
        for bi, band in enumerate((self.band1, self.band2, self.hp)):
            for j in range(5):
                d[f"bq{bi}_{j}"] = band.lag[j]
            d[f"bq{bi}_r0"] = band.reg0[0]
            d[f"bq{bi}_r1"] = band.reg1[0]
        d["hash"] = self.ring_hash & ((1 << 64) - 1)
        return d


class ConditionerModel:
    """One Conditioner instance: audio-rate datapath + block control pass."""

    def __init__(self, params, name="conditioner"):
        self.p = params if isinstance(params, ConditionerParams) \
            else ConditionerParams(params)
        self.st = ConditionerState(name)
        self.ctrl = None
        self._pending = 0
        self.initialized = False

    # ---------------- lifecycle --------------------------------------------
    def initialize(self):
        """Fresh spawn + init() (engine patch load: loadFx(false, true)
        re-creates every FX object). Everything is constructor state."""
        self.st = ConditionerState(self.st.name)
        self._setvars()          # first_run: coefficients start instantly
        self._pending |= FLAG_FRESH
        self.initialized = True

    def suspend(self):
        """Engine suspend() == init() on an EXISTING object (stopSound /
        fx_suspend_bitmask / FX preset reload). init() clears the limiter
        state and re-targets the biquads (setvars(true), which is a no-op
        beyond setvars) but does NOT call BiquadFilter::suspend(): biquad
        registers and coefficient lags survive, as do the four lipol ramps
        and the Effect ringout counter."""
        self.st.clear_limiter()
        self._setvars()
        self._pending |= FLAG_SUSPEND

    def _setvars(self):
        st = self.st
        st.band1.new_targets(coeff_peak_eq(calc_omega_d(_BASS_SCFREQ), _EQ_BW,
                                           self.p.bass_db))
        st.band2.new_targets(coeff_peak_eq(calc_omega_d(_TREBLE_SCFREQ), _EQ_BW,
                                           self.p.treble_db))
        st.hp.new_targets(coeff_hp(calc_omega_d(self.p.hpwidth_semitones / 12.0),
                                   _HP_Q))

    def _raw_targets(self):
        pregain = db_to_linear_d(-self.p.threshold_db)
        bal = self.p.balance_f

        def c1(x):
            return min(1.0, max(-1.0, x))
        return (to_q(pregain * 0.5 * c1(1.0 - bal), G_FMT),
                to_q(pregain * 0.5 * c1(1.0 + bal), G_FMT),
                to_q(c1(self.p.width_f), G_FMT),
                to_q(db_to_linear_d(self.p.gain_db), G_FMT))

    def _emit_ctrl(self, attack_q, release_q, raws, control_only):
        flags = self._pending
        self._pending = 0
        if not self.p.bass_deactivated:
            flags |= FLAG_BASS_ON
        if not self.p.treble_deactivated:
            flags |= FLAG_TREBLE_ON
        if not self.p.hpwidth_deactivated:
            flags |= FLAG_HP_ON
        if control_only:
            flags |= FLAG_CONTROL_ONLY
        words = [attack_q, release_q] + list(raws)
        for band in (self.st.band1, self.st.band2, self.st.hp):
            words += list(band.tgt)
        words.append(flags)
        assert len(words) == CTRL_WORDS
        self.ctrl = words

    def _coeffs_q(self):
        a, r = attack_release_f32(self.p.attack_f, self.p.release_f)
        return to_q(a, C_FMT), to_q(r, C_FMT)

    def _envelope_step(self, la_c, attack_q, release_q):
        st = self.st
        st.filtered_lamax = qadd(
            qmul(qsub(ONE_C, attack_q, C_FMT), st.filtered_lamax, C_FMT, C_FMT, C_FMT),
            qmul(attack_q, la_c, C_FMT, C_FMT, C_FMT), C_FMT)
        st.filtered_lamax2 = qadd(
            qmul(qsub(ONE_C, release_q, C_FMT), st.filtered_lamax2, C_FMT, C_FMT, C_FMT),
            qmul(release_q, st.filtered_lamax, C_FMT, C_FMT, C_FMT), C_FMT)
        if st.filtered_lamax > st.filtered_lamax2:
            st.filtered_lamax2 = st.filtered_lamax
        st.gain = qdiv(ONE_C, st.filtered_lamax2, C_FMT)   # declared deviation

    # ---------------- audio ------------------------------------------------
    def process_block(self, in_l, in_r):
        """ConditionerEffect::process on one 32-sample block (Q10.21)."""
        if not self.initialized:
            self.initialize()
        st = self.st
        attack_q, release_q = self._coeffs_q()
        self._setvars()

        data_l = list(in_l)
        data_r = list(in_r)
        if not self.p.bass_deactivated:
            for k in range(BLOCK):
                data_l[k], data_r[k] = st.band1.process_sample(data_l[k], data_r[k])
        if not self.p.treble_deactivated:
            for k in range(BLOCK):
                data_l[k], data_r[k] = st.band2.process_sample(data_l[k], data_r[k])

        raws = self._raw_targets()
        st.ampL.set_target_smoothed(raws[0])
        st.ampR.set_target_smoothed(raws[1])
        st.width_s.set_target_smoothed(raws[2])
        st.postamp.set_target_smoothed(raws[3])

        m = [half_toward_zero(data_l[k] + data_r[k]) for k in range(BLOCK)]
        s = [half_toward_zero(data_l[k] - data_r[k]) for k in range(BLOCK)]
        if not self.p.hpwidth_deactivated:
            # mono process_block(float*): channel-0 registers only; the
            # shared stereo class's channel 1 is fed 0 and never read
            for k in range(BLOCK):
                s[k], _ = st.hp.process_sample(s[k], 0)
        for k in range(BLOCK):
            s[k] = st.width_s.mul_sample(st.width_s.line_value(k), s[k])
        for k in range(BLOCK):
            data_l[k] = qadd(m[k], s[k], A_FMT)
            data_r[k] = qsub(m[k], s[k], A_FMT)
        for k in range(BLOCK):
            data_l[k] = st.ampL.mul_sample(st.ampL.line_value(k), data_l[k])
            data_r[k] = st.ampR.mul_sample(st.ampR.line_value(k), data_r[k])

        out_l = [0] * BLOCK
        out_r = [0] * BLOCK
        for k in range(BLOCK):
            bp = st.bufpos
            d_l = st.delayed[0][bp]
            d_r = st.delayed[1][bp]
            la_c = st.lamax[LA_READ_INDEX]
            st.state_reads += 3
            la_c = isqrt_c(qadd(la_c, la_c, C_FMT))      # sqrt(2 * la)
            if la_c < ONE_C:                               # max(1.f, la)
                la_c = ONE_C
            self._envelope_step(la_c, attack_q, release_q)

            st.ring_hash += (data_l[k] - d_l) * (bp + 1) + (data_r[k] - d_r) * (bp + 129)
            st.delayed[0][bp] = data_l[k]
            st.delayed[1][bp] = data_r[k]
            a_l = abs(data_l[k])
            a_r = abs(data_r[k])
            leaf = a_l if a_l >= a_r else a_r
            leaf_sq = qmul(leaf, leaf, A_FMT, A_FMT, C_FMT)   # exact promote
            st.ring_hash += (leaf_sq - st.lamax[bp]) * (bp + 257)
            st.lamax[bp] = leaf_sq
            st.state_writes += 3

            out_l[k] = qmul(st.gain, d_l, C_FMT, A_FMT, A_FMT)
            out_r[k] = qmul(st.gain, d_r, C_FMT, A_FMT, A_FMT)
            st.bufpos = (bp + 1) & LOOKAHEAD_MASK

        for k in range(BLOCK):
            g = st.postamp.line_value(k)
            out_l[k] = st.postamp.mul_sample(g, out_l[k])
            out_r[k] = st.postamp.mul_sample(g, out_r[k])

        self._emit_ctrl(attack_q, release_q, raws, control_only=False)
        return out_l, out_r

    def process_only_control(self, in_l, in_r):
        """ConditionerEffect::process_only_control: the audio buffers are NOT
        touched (output == input), no setvars, no lipol targets; the envelope
        trackers advance 32 steps with la = 1 and gain = 1/filtered_lamax2."""
        if not self.initialized:
            self.initialize()
        attack_q, release_q = self._coeffs_q()
        for _ in range(BLOCK):
            self._envelope_step(ONE_C, attack_q, release_q)
        self._emit_ctrl(attack_q, release_q, self._raw_targets(), control_only=True)
        return list(in_l), list(in_r)

    def process_ringout(self, in_l, in_r, indata_present):
        """Effect::process_ringout. Returns (out_l, out_r, processed)."""
        if not self.initialized:
            self.initialize()
        st = self.st
        if indata_present:
            st.ringout = 0
        else:
            st.ringout += 1
        if st.ringout < RINGOUT_DECAY_BLOCKS or st.ringout == 0:
            ol, orr = self.process_block(in_l, in_r)
            return ol, orr, True
        ol, orr = self.process_only_control(in_l, in_r)
        return ol, orr, False


def tail_coverage_check(n_blocks_compared, last_present_block):
    """Declared tail-span check (acceptance 'Tails').

    A comparison covers this leaf's tail only if it includes every block the
    engine still runs process() for after the last input-present block
    (TAIL_PROCESS_BLOCKS = get_ringout_decay() - 1 = 99) PLUS the first
    control-only block (the process -> process_only_control transition).
    Returns (ok, required_blocks)."""
    required = last_present_block + 1 + TAIL_PROCESS_BLOCKS + 1
    return n_blocks_compared >= required, required


def model_revision():
    """sha256 of this file (frozen-revision pin for traces/harnesses)."""
    with open(os.path.abspath(__file__), "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()
